from pandas import DatetimeIndex, Timestamp
from numpy import array as numpy_array

from zoneinfo import ZoneInfo
from math import radians
from pvgisprototype import TrueSolarTime
from pvgisprototype.constants import DATA_TYPE_DEFAULT
from pvgisprototype.constants import ARRAY_BACKEND_DEFAULT
from pvgisprototype import Longitude
from pvgisprototype.constants import RADIANS
from pvgisprototype.constants import MINUTES

cases = [
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2024, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([718.5555633919768], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2023, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([718.6717631997775], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2022, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([718.6717631997775], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2021, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([718.6717631997775], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2020, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([718.5555633919768], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([718.6717631997775], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2018, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([718.6717631997775], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2017, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([718.6717631997775], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2016, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([718.5555633919768], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2015, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([718.6717631997775], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2014, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([718.6717631997775], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2013, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([718.6717631997775], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2012, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([718.5555633919768], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2011, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([718.6717631997775], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2010, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([718.6717631997775], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2020, month=12, day=31, hour=0, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([-2.228653953567693], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2020, month=12, day=31, hour=23, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([1377.3388487570096], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2020, month=1, day=1, hour=0, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([-2.90416896], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=0, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([-2.90416896], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=1, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([57.09583104], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=2, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([117.09583104000001], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=3, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([177.09583104], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=4, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([237.09583104], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=5, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([297.09583104], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=6, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([357.09583104], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=7, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([417.09583104], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=8, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([477.09583104], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=9, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([537.09583104], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=10, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([597.09583104], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=11, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([837.09583104], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([897.09583104], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(180.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=13, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([1497.0771318959928], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(180.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=18, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([1796.9837373236796], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=14, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([1017.0584394547448], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=15, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([1077.0397537465833], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=16, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([1137.0210748018214], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=17, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([1197.0024026507588], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=18, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([1256.9837373236796], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=19, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([1316.9650788508548], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=20, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([1376.94642726254], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(55.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=20, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([1416.94642726254], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(10.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=20, minute=0, second=0)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([1236.94642726254], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(43.19909177646344), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=1990, month=2, day=5, hour=9, minute=24, second=16)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([723.3410309894955], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(173.45895203819822), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=1990, month=3, day=3, hour=18, minute=17, second=6)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([1778.4482971607397], dtype='float32'), unit=MINUTES)),
    ({
        "longitude": Longitude(value=radians(51.881130269232834), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=1997, month=3, day=5, hour=17, minute=0, second=28)]),
        "timezone": ZoneInfo("UTC"),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     TrueSolarTime(value=numpy_array([1215.903608265079], dtype='float32'), unit=MINUTES)),
]
cases_ids = [
    'Input: Longitude:0.00_2024-6-21 12:0:0',
    'Input: Longitude:0.00_2023-6-21 12:0:0',
    'Input: Longitude:0.00_2022-6-21 12:0:0',
    'Input: Longitude:0.00_2021-6-21 12:0:0',
    'Input: Longitude:0.00_2020-6-21 12:0:0',
    'Input: Longitude:0.00_2019-6-21 12:0:0',
    'Input: Longitude:0.00_2018-6-21 12:0:0',
    'Input: Longitude:0.00_2017-6-21 12:0:0',
    'Input: Longitude:0.00_2016-6-21 12:0:0',
    'Input: Longitude:0.00_2015-6-21 12:0:0',
    'Input: Longitude:0.00_2014-6-21 12:0:0',
    'Input: Longitude:0.00_2013-6-21 12:0:0',
    'Input: Longitude:0.00_2012-6-21 12:0:0',
    'Input: Longitude:0.00_2011-6-21 12:0:0',
    'Input: Longitude:0.00_2010-6-21 12:0:0',
    'Input: Longitude:0.00_2020-12-31 0:0:0',
    'Input: Longitude:0.00_2020-12-31 23:0:0',
    'Input: Longitude:0.00_2020-1-1 0:0:0',
    'Input: Longitude:0.00_2019-1-1 0:0:0',
    'Input: Longitude:0.00_2019-1-1 1:0:0',
    'Input: Longitude:0.00_2019-1-1 2:0:0',
    'Input: Longitude:0.00_2019-1-1 3:0:0',
    'Input: Longitude:0.00_2019-1-1 4:0:0',
    'Input: Longitude:0.00_2019-1-1 5:0:0',
    'Input: Longitude:0.00_2019-1-1 6:0:0',
    'Input: Longitude:0.00_2019-1-1 7:0:0',
    'Input: Longitude:0.00_2019-1-1 8:0:0',
    'Input: Longitude:0.00_2019-1-1 9:0:0',
    'Input: Longitude:0.00_2019-1-1 10:0:0',
    'Input: Longitude:45.00_2019-1-1 11:0:0',
    'Input: Longitude:45.00_2019-1-1 12:0:0',
    'Input: Longitude:180.00_2019-1-1 13:0:0',
    'Input: Longitude:180.00_2019-1-1 18:0:0',
    'Input: Longitude:45.00_2019-1-1 14:0:0',
    'Input: Longitude:45.00_2019-1-1 15:0:0',
    'Input: Longitude:45.00_2019-1-1 16:0:0',
    'Input: Longitude:45.00_2019-1-1 17:0:0',
    'Input: Longitude:45.00_2019-1-1 18:0:0',
    'Input: Longitude:45.00_2019-1-1 19:0:0',
    'Input: Longitude:45.00_2019-1-1 20:0:0',
    'Input: Longitude:55.00_2019-1-1 20:0:0',
    'Input: Longitude:10.00_2019-1-1 20:0:0',
    'Input: Longitude:43.20_1990-2-5 9:24:16',
    'Input: Longitude:173.46_1990-3-3 18:17:6',
    'Input: Longitude:51.88_1997-3-5 17:0:28',
]
