#
# Copyright (C) 2025 European Union
#  
#  
# Licensed under the EUPL, Version 1.2 or – as soon they will be approved by the
# European Commission – subsequent versions of the EUPL (the “Licence”);
# You may not use this work except in compliance with the Licence.
# You may obtain a copy of the Licence at:
# *
# https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12 
# *
# Unless required by applicable law or agreed to in writing, software distributed under
# the Licence is distributed on an “AS IS” basis, WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied. See the Licence for the specific language
# governing permissions and limitations under the Licence.
#
from pandas import DatetimeIndex, Timestamp
from numpy import array as numpy_array

from pvgisprototype import EventHourAngle
from pvgisprototype.constants import DATA_TYPE_DEFAULT
from pvgisprototype.constants import ARRAY_BACKEND_DEFAULT
from pvgisprototype import Latitude
from pvgisprototype.constants import RADIANS
from pvgisprototype import RefractedSolarZenith
cases = [
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2024, month=6, day=21, hour=12, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([2.04], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2023, month=6, day=21, hour=12, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([2.04], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2022, month=6, day=21, hour=12, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([2.04], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2021, month=6, day=21, hour=12, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([2.04], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2020, month=6, day=21, hour=12, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([2.04], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2020, month=6, day=21, hour=15, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([2.04], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2020, month=6, day=21, hour=9, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([2.04], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=6, day=21, hour=12, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([2.04], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2018, month=6, day=21, hour=12, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([2.04], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2017, month=6, day=21, hour=12, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([2.04], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2016, month=6, day=21, hour=12, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([2.04], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2015, month=6, day=21, hour=12, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([2.04], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2014, month=6, day=21, hour=12, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([2.04], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2013, month=6, day=21, hour=12, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([2.04], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2012, month=6, day=21, hour=12, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([2.04], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2011, month=6, day=21, hour=12, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([2.04], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2010, month=6, day=21, hour=12, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([2.04], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2020, month=12, day=31, hour=0, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.15], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2020, month=12, day=31, hour=23, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.15], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2020, month=1, day=1, hour=0, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=0, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=1, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=2, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=3, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=4, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=5, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=6, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=7, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=8, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=9, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=10, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.0 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=11, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.59], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=12, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=13, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=14, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=15, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=16, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=17, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=18, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=19, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=20, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.16], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=0.9599 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=20, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([0.95], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=1.2217 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=20, minute=0, second=0)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([0.0], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=-1.3637 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2018, month=2, day=1, hour=5, minute=52, second=54)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([3.14], dtype='float32'), unit=RADIANS)),
    ({
        "latitude": Latitude(value=1.252 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2012, month=9, day=9, hour=18, minute=47, second=15)]),
        "refracted_solar_zenith": RefractedSolarZenith(value=numpy_array([1.585334919464], dtype='float32'), unit=RADIANS),
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     EventHourAngle(value=numpy_array([1.91], dtype='float32'), unit=RADIANS)),
]
cases_ids = [
    'Input: Latitude:45.00_2024-6-21T12:0:0',
    'Input: Latitude:45.00_2023-6-21T12:0:0',
    'Input: Latitude:45.00_2022-6-21T12:0:0',
    'Input: Latitude:45.00_2021-6-21T12:0:0',
    'Input: Latitude:45.00_2020-6-21T12:0:0',
    'Input: Latitude:45.00_2020-6-21T15:0:0',
    'Input: Latitude:45.00_2020-6-21T9:0:0',
    'Input: Latitude:45.00_2019-6-21T12:0:0',
    'Input: Latitude:45.00_2018-6-21T12:0:0',
    'Input: Latitude:45.00_2017-6-21T12:0:0',
    'Input: Latitude:45.00_2016-6-21T12:0:0',
    'Input: Latitude:45.00_2015-6-21T12:0:0',
    'Input: Latitude:45.00_2014-6-21T12:0:0',
    'Input: Latitude:45.00_2013-6-21T12:0:0',
    'Input: Latitude:45.00_2012-6-21T12:0:0',
    'Input: Latitude:45.00_2011-6-21T12:0:0',
    'Input: Latitude:45.00_2010-6-21T12:0:0',
    'Input: Latitude:45.00_2020-12-31T0:0:0',
    'Input: Latitude:45.00_2020-12-31T23:0:0',
    'Input: Latitude:45.00_2020-1-1T0:0:0',
    'Input: Latitude:45.00_2019-1-1T0:0:0',
    'Input: Latitude:45.00_2019-1-1T1:0:0',
    'Input: Latitude:45.00_2019-1-1T2:0:0',
    'Input: Latitude:45.00_2019-1-1T3:0:0',
    'Input: Latitude:45.00_2019-1-1T4:0:0',
    'Input: Latitude:45.00_2019-1-1T5:0:0',
    'Input: Latitude:45.00_2019-1-1T6:0:0',
    'Input: Latitude:45.00_2019-1-1T7:0:0',
    'Input: Latitude:45.00_2019-1-1T8:0:0',
    'Input: Latitude:45.00_2019-1-1T9:0:0',
    'Input: Latitude:45.00_2019-1-1T10:0:0',
    'Input: Latitude:0.00_2019-1-1T11:0:0',
    'Input: Latitude:45.00_2019-1-1T12:0:0',
    'Input: Latitude:45.00_2019-1-1T13:0:0',
    'Input: Latitude:45.00_2019-1-1T14:0:0',
    'Input: Latitude:45.00_2019-1-1T15:0:0',
    'Input: Latitude:45.00_2019-1-1T16:0:0',
    'Input: Latitude:45.00_2019-1-1T17:0:0',
    'Input: Latitude:45.00_2019-1-1T18:0:0',
    'Input: Latitude:45.00_2019-1-1T19:0:0',
    'Input: Latitude:45.00_2019-1-1T20:0:0',
    'Input: Latitude:55.00_2019-1-1T20:0:0',
    'Input: Latitude:70.00_2019-1-1T20:0:0',
    'Input: Latitude:-78.13_2018-2-1T5:52:54',
    'Input: Latitude:71.74_2012-9-9T18:47:15',
]
