from pandas import DatetimeIndex, Timestamp
from numpy import array as numpy_array

from math import radians
from zoneinfo import ZoneInfo
from pvgisprototype import SolarAzimuth
from pvgisprototype.constants import DATA_TYPE_DEFAULT
from pvgisprototype.constants import ARRAY_BACKEND_DEFAULT
from pvgisprototype import Latitude
from pvgisprototype import Longitude
from pvgisprototype.constants import RADIANS
from pvgisprototype.constants import MINUTES

cases = [
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2024, month=6, day=21, hour=12, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1961490176402676], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2023, month=6, day=21, hour=12, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.196171145167929], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2022, month=6, day=21, hour=12, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.196171145167929], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2021, month=6, day=21, hour=12, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.196171145167929], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2020, month=6, day=21, hour=12, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1961490176402676], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=6, day=21, hour=12, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.196171145167929], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2018, month=6, day=21, hour=12, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.196171145167929], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2017, month=6, day=21, hour=12, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.196171145167929], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2016, month=6, day=21, hour=12, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1961490176402676], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2015, month=6, day=21, hour=12, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.196171145167929], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2014, month=6, day=21, hour=12, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.196171145167929], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2013, month=6, day=21, hour=12, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.196171145167929], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2012, month=6, day=21, hour=12, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1961490176402676], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2011, month=6, day=21, hour=12, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.196171145167929], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2010, month=6, day=21, hour=12, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.196171145167929], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2020, month=12, day=31, hour=0, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1420120998852776], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2020, month=12, day=31, hour=23, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1523911125203665], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2020, month=1, day=1, hour=0, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1421371413334738], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=0, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1421371413334738], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=1, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1515491168678937], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=2, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.158999883839632], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=3, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1640163328182327], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=4, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.167786299675567], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=5, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1709825008560597], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=6, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1739677964660076], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=7, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1769670951554336], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=8, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.180143641249609], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=9, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1836234992856376], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(0.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=10, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1874851735430045], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(45.0), unit=RADIANS),
        "latitude": Latitude(value=radians(0.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=11, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.181510008877271], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(45.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=12, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1839799468729004], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(180.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=13, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1515453310898325], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(180.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=18, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1739577841547733], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(45.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=14, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1772651708528334], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(45.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=15, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1742551608405627], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(45.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=16, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1712769205211644], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(45.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=17, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.16811398424051], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(45.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=18, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1644229203951904], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(45.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=19, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.15957349193418], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(45.0), unit=RADIANS),
        "latitude": Latitude(value=radians(45.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=20, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1524277882539926], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(55.0), unit=RADIANS),
        "latitude": Latitude(value=radians(55.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=20, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.144630266044248], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(10.0), unit=RADIANS),
        "latitude": Latitude(value=radians(70.0), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=20, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.159839554985979], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(43.19909177646344), unit=RADIANS),
        "latitude": Latitude(value=radians(12.263850048516248), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=1990, month=2, day=5, hour=9, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.195911471632374], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(173.45895203819822), unit=RADIANS),
        "latitude": Latitude(value=radians(58.94236356417855), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=1990, month=3, day=3, hour=18, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.168712030651362], dtype='float32'), unit=RADIANS)),
    ({
        "longitude": Longitude(value=radians(51.881130269232834), unit=RADIANS),
        "latitude": Latitude(value=radians(74.58274517175076), unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=1997, month=3, day=5, hour=17, minute=0, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": False,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": ARRAY_BACKEND_DEFAULT,
    },
     SolarAzimuth(value=numpy_array([3.1593920472481165], dtype='float32'), unit=RADIANS)),
]
cases_ids = [
    'Input: Latitude,Longitude:45.00-0.00_2024-6-21T12:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2023-6-21T12:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2022-6-21T12:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2021-6-21T12:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2020-6-21T12:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2019-6-21T12:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2018-6-21T12:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2017-6-21T12:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2016-6-21T12:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2015-6-21T12:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2014-6-21T12:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2013-6-21T12:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2012-6-21T12:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2011-6-21T12:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2010-6-21T12:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2020-12-31T0:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2020-12-31T23:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2020-1-1T0:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2019-1-1T0:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2019-1-1T1:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2019-1-1T2:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2019-1-1T3:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2019-1-1T4:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2019-1-1T5:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2019-1-1T6:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2019-1-1T7:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2019-1-1T8:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2019-1-1T9:0:0',
    'Input: Latitude,Longitude:45.00-0.00_2019-1-1T10:0:0',
    'Input: Latitude,Longitude:0.00-45.00_2019-1-1T11:0:0',
    'Input: Latitude,Longitude:45.00-45.00_2019-1-1T12:0:0',
    'Input: Latitude,Longitude:45.00-180.00_2019-1-1T13:0:0',
    'Input: Latitude,Longitude:45.00-180.00_2019-1-1T18:0:0',
    'Input: Latitude,Longitude:45.00-45.00_2019-1-1T14:0:0',
    'Input: Latitude,Longitude:45.00-45.00_2019-1-1T15:0:0',
    'Input: Latitude,Longitude:45.00-45.00_2019-1-1T16:0:0',
    'Input: Latitude,Longitude:45.00-45.00_2019-1-1T17:0:0',
    'Input: Latitude,Longitude:45.00-45.00_2019-1-1T18:0:0',
    'Input: Latitude,Longitude:45.00-45.00_2019-1-1T19:0:0',
    'Input: Latitude,Longitude:45.00-45.00_2019-1-1T20:0:0',
    'Input: Latitude,Longitude:55.00-55.00_2019-1-1T20:0:0',
    'Input: Latitude,Longitude:70.00-10.00_2019-1-1T20:0:0',
    'Input: Latitude,Longitude:12.26-43.20_1990-2-5T9:24:16',
    'Input: Latitude,Longitude:58.94-173.46_1990-3-3T18:17:6',
    'Input: Latitude,Longitude:74.58-51.88_1997-3-5T17:0:28',
]
