from pandas import DatetimeIndex, Timestamp
from numpy import array as numpy_array

from zoneinfo import ZoneInfo
from pvgisprototype.constants import DATA_TYPE_DEFAULT
from pvgisprototype import Latitude
from pvgisprototype import Longitude
from pvgisprototype.constants import RADIANS

cases = [
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2024, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([178.801], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2023, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([178.892], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2022, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([178.865], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2021, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([178.843], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2020, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([178.809], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2020, month=6, day=21, hour=15, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([254.252], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2020, month=6, day=21, hour=9, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([104.876], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([178.912], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2018, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([178.884], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2017, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([178.863], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2016, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([178.833], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2015, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([178.925], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2014, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([178.9], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2013, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([178.873], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2012, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([178.83], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2011, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([178.928], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2010, month=6, day=21, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([178.895], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=7, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([116.025], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=8, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([126.445], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=9, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([137.858], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=10, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([150.526], dtype='float32')),
    ({
        "longitude": Longitude(value=0.7854, unit=RADIANS),
        "latitude": Latitude(value=0.0 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=11, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([228.923], dtype='float32')),
    ({
        "longitude": Longitude(value=0.7854, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=12, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([220.773], dtype='float32')),
    ({
        "longitude": Longitude(value=0.7854, unit=RADIANS),
        "latitude": Latitude(value=0.7854 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=1, day=1, hour=14, minute=0, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([242.845], dtype='float32')),
    ({
        "longitude": Longitude(value=-0.6512, unit=RADIANS),
        "latitude": Latitude(value=-0.4019 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2013, month=1, day=19, hour=7, minute=7, second=36)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([118.212], dtype='float32')),
    ({
        "longitude": Longitude(value=3.0972, unit=RADIANS),
        "latitude": Latitude(value=1.2083 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2010, month=3, day=3, hour=3, minute=45, second=58)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([230.862], dtype='float32')),
    ({
        "longitude": Longitude(value=-0.9997, unit=RADIANS),
        "latitude": Latitude(value=-0.0899 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2006, month=3, day=27, hour=13, minute=18, second=15)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([79.554], dtype='float32')),
    ({
        "longitude": Longitude(value=1.1566, unit=RADIANS),
        "latitude": Latitude(value=-0.8077 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=12, day=7, hour=2, minute=21, second=48)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([96.646], dtype='float32')),
    ({
        "longitude": Longitude(value=-0.0232, unit=RADIANS),
        "latitude": Latitude(value=-1.0375 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2005, month=4, day=16, hour=15, minute=25, second=49)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([309.965], dtype='float32')),
    ({
        "longitude": Longitude(value=0.3971, unit=RADIANS),
        "latitude": Latitude(value=1.1308 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2018, month=8, day=10, hour=10, minute=49, second=48)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([184.904], dtype='float32')),
    ({
        "longitude": Longitude(value=2.7765, unit=RADIANS),
        "latitude": Latitude(value=-0.7725 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2008, month=5, day=27, hour=5, minute=58, second=4)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([299.38], dtype='float32')),
    ({
        "longitude": Longitude(value=-2.6461, unit=RADIANS),
        "latitude": Latitude(value=-0.3735 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2017, month=7, day=5, hour=3, minute=5, second=11)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([297.263], dtype='float32')),
    ({
        "longitude": Longitude(value=-2.0637, unit=RADIANS),
        "latitude": Latitude(value=1.1793 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2005, month=5, day=17, hour=20, minute=15, second=12)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([188.18], dtype='float32')),
    ({
        "longitude": Longitude(value=1.641, unit=RADIANS),
        "latitude": Latitude(value=-0.0041 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=12, day=10, hour=9, minute=0, second=31)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([241.629], dtype='float32')),
    ({
        "longitude": Longitude(value=1.7546, unit=RADIANS),
        "latitude": Latitude(value=1.5643 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=6, day=7, hour=13, minute=17, second=0)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([300.2], dtype='float32')),
    ({
        "longitude": Longitude(value=2.7509, unit=RADIANS),
        "latitude": Latitude(value=1.5194 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2011, month=8, day=18, hour=22, minute=25, second=39)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([132.537], dtype='float32')),
    ({
        "longitude": Longitude(value=2.933, unit=RADIANS),
        "latitude": Latitude(value=0.3686 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2018, month=1, day=8, hour=6, minute=33, second=50)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([247.447], dtype='float32')),
    ({
        "longitude": Longitude(value=0.9963, unit=RADIANS),
        "latitude": Latitude(value=-1.3984 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2008, month=10, day=20, hour=18, minute=33, second=43)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([200.285], dtype='float32')),
    ({
        "longitude": Longitude(value=-0.4879, unit=RADIANS),
        "latitude": Latitude(value=-0.9002 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=4, day=11, hour=14, minute=11, second=39)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([354.653], dtype='float32')),
    ({
        "longitude": Longitude(value=-0.2609, unit=RADIANS),
        "latitude": Latitude(value=0.5493 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2010, month=4, day=15, hour=20, minute=20, second=8)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([289.308], dtype='float32')),
    ({
        "longitude": Longitude(value=-1.5745, unit=RADIANS),
        "latitude": Latitude(value=-0.996 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2020, month=11, day=4, hour=11, minute=42, second=49)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([98.954], dtype='float32')),
    ({
        "longitude": Longitude(value=-0.0597, unit=RADIANS),
        "latitude": Latitude(value=-0.0405 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2007, month=10, day=24, hour=8, minute=10, second=38)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([102.402], dtype='float32')),
    ({
        "longitude": Longitude(value=-1.6833, unit=RADIANS),
        "latitude": Latitude(value=1.3804 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2017, month=9, day=12, hour=23, minute=31, second=40)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([258.394], dtype='float32')),
    ({
        "longitude": Longitude(value=-2.456, unit=RADIANS),
        "latitude": Latitude(value=-0.8815 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2007, month=5, day=4, hour=2, minute=43, second=58)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([286.9], dtype='float32')),
    ({
        "longitude": Longitude(value=2.5514, unit=RADIANS),
        "latitude": Latitude(value=0.8159 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2007, month=12, day=14, hour=5, minute=19, second=59)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([223.256], dtype='float32')),
    ({
        "longitude": Longitude(value=0.1558, unit=RADIANS),
        "latitude": Latitude(value=0.7732 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2011, month=10, day=6, hour=12, minute=13, second=16)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([199.55], dtype='float32')),
    ({
        "longitude": Longitude(value=0.9874, unit=RADIANS),
        "latitude": Latitude(value=-1.1118 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2012, month=3, day=11, hour=2, minute=32, second=4)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([89.719], dtype='float32')),
    ({
        "longitude": Longitude(value=-2.6935, unit=RADIANS),
        "latitude": Latitude(value=0.485 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2017, month=7, day=10, hour=2, minute=57, second=42)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([281.664], dtype='float32')),
    ({
        "longitude": Longitude(value=-1.9394, unit=RADIANS),
        "latitude": Latitude(value=-0.1433 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2018, month=1, day=22, hour=20, minute=47, second=48)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([235.006], dtype='float32')),
    ({
        "longitude": Longitude(value=0.3833, unit=RADIANS),
        "latitude": Latitude(value=-1.3165 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2017, month=6, day=6, hour=13, minute=12, second=13)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([322.485], dtype='float32')),
    ({
        "longitude": Longitude(value=-1.2923, unit=RADIANS),
        "latitude": Latitude(value=-1.205 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2009, month=9, day=19, hour=18, minute=31, second=39)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([333.193], dtype='float32')),
    ({
        "longitude": Longitude(value=-1.7914, unit=RADIANS),
        "latitude": Latitude(value=1.5368 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2019, month=10, day=6, hour=6, minute=5, second=55)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([351.745], dtype='float32')),
    ({
        "longitude": Longitude(value=0.2899, unit=RADIANS),
        "latitude": Latitude(value=0.6048 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2013, month=7, day=8, hour=18, minute=19, second=56)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([299.759], dtype='float32')),
    ({
        "longitude": Longitude(value=-0.7495, unit=RADIANS),
        "latitude": Latitude(value=-0.1922 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2010, month=3, day=28, hour=16, minute=20, second=20)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([303.075], dtype='float32')),
    ({
        "longitude": Longitude(value=0.1772, unit=RADIANS),
        "latitude": Latitude(value=0.5886 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2013, month=9, day=9, hour=4, minute=11, second=25)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([76.362], dtype='float32')),
    ({
        "longitude": Longitude(value=1.1104, unit=RADIANS),
        "latitude": Latitude(value=-0.222 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2012, month=4, day=14, hour=9, minute=26, second=9)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([310.672], dtype='float32')),
    ({
        "longitude": Longitude(value=-2.2963, unit=RADIANS),
        "latitude": Latitude(value=0.0705 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2008, month=4, day=6, hour=3, minute=23, second=45)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([277.241], dtype='float32')),
    ({
        "longitude": Longitude(value=-0.8619, unit=RADIANS),
        "latitude": Latitude(value=0.7238 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2017, month=12, day=22, hour=17, minute=4, second=37)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([206.46], dtype='float32')),
    ({
        "longitude": Longitude(value=-2.0505, unit=RADIANS),
        "latitude": Latitude(value=-1.2726 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2007, month=7, day=26, hour=17, minute=49, second=18)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([29.91], dtype='float32')),
    ({
        "longitude": Longitude(value=1.1026, unit=RADIANS),
        "latitude": Latitude(value=0.7415 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2010, month=10, day=21, hour=12, minute=56, second=11)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([256.058], dtype='float32')),
    ({
        "longitude": Longitude(value=-2.6581, unit=RADIANS),
        "latitude": Latitude(value=-0.806 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2010, month=6, day=8, hour=3, minute=37, second=47)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([291.314], dtype='float32')),
    ({
        "longitude": Longitude(value=0.8528, unit=RADIANS),
        "latitude": Latitude(value=-0.9354 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2013, month=1, day=12, hour=12, minute=54, second=20)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([280.668], dtype='float32')),
    ({
        "longitude": Longitude(value=-1.6932, unit=RADIANS),
        "latitude": Latitude(value=-1.4294 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2012, month=1, day=7, hour=6, minute=7, second=6)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([186.41], dtype='float32')),
    ({
        "longitude": Longitude(value=-2.0426, unit=RADIANS),
        "latitude": Latitude(value=-0.5254 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2009, month=8, day=24, hour=17, minute=47, second=31)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([40.532], dtype='float32')),
    ({
        "longitude": Longitude(value=-1.5001, unit=RADIANS),
        "latitude": Latitude(value=0.4727 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2016, month=3, day=2, hour=22, minute=9, second=5)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([250.869], dtype='float32')),
    ({
        "longitude": Longitude(value=-2.2267, unit=RADIANS),
        "latitude": Latitude(value=0.597 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2016, month=10, day=27, hour=2, minute=17, second=21)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([259.72], dtype='float32')),
    ({
        "longitude": Longitude(value=1.1945, unit=RADIANS),
        "latitude": Latitude(value=-0.6147 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2020, month=4, day=11, hour=1, minute=30, second=55)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([82.582], dtype='float32')),
    ({
        "longitude": Longitude(value=0.832, unit=RADIANS),
        "latitude": Latitude(value=-0.5548 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2006, month=9, day=1, hour=13, minute=43, second=45)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([285.784], dtype='float32')),
    ({
        "longitude": Longitude(value=0.0589, unit=RADIANS),
        "latitude": Latitude(value=1.3196 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2016, month=12, day=14, hour=14, minute=13, second=9)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([215.223], dtype='float32')),
    ({
        "longitude": Longitude(value=2.2665, unit=RADIANS),
        "latitude": Latitude(value=-0.1341 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2013, month=7, day=21, hour=23, minute=22, second=9)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([63.828], dtype='float32')),
    ({
        "longitude": Longitude(value=-1.1366, unit=RADIANS),
        "latitude": Latitude(value=-1.1908 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2009, month=8, day=20, hour=12, minute=31, second=28)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([56.041], dtype='float32')),
    ({
        "longitude": Longitude(value=-0.5617, unit=RADIANS),
        "latitude": Latitude(value=-1.2701 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2016, month=2, day=1, hour=12, minute=6, second=34)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([38.511], dtype='float32')),
    ({
        "longitude": Longitude(value=-2.7065, unit=RADIANS),
        "latitude": Latitude(value=-1.499 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2013, month=2, day=23, hour=2, minute=22, second=7)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([302.213], dtype='float32')),
    ({
        "longitude": Longitude(value=2.4386, unit=RADIANS),
        "latitude": Latitude(value=-0.2609 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2018, month=6, day=5, hour=4, minute=40, second=21)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([321.116], dtype='float32')),
    ({
        "longitude": Longitude(value=1.7212, unit=RADIANS),
        "latitude": Latitude(value=1.0468 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2011, month=4, day=16, hour=13, minute=10, second=22)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([297.758], dtype='float32')),
    ({
        "longitude": Longitude(value=2.5286, unit=RADIANS),
        "latitude": Latitude(value=1.1932 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2020, month=1, day=19, hour=3, minute=46, second=26)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([197.644], dtype='float32')),
    ({
        "longitude": Longitude(value=2.0413, unit=RADIANS),
        "latitude": Latitude(value=-0.0678 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2017, month=9, day=21, hour=3, minute=46, second=27)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([46.157], dtype='float32')),
    ({
        "longitude": Longitude(value=-1.5741, unit=RADIANS),
        "latitude": Latitude(value=1.2886 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2009, month=9, day=21, hour=8, minute=34, second=12)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([41.122], dtype='float32')),
    ({
        "longitude": Longitude(value=-0.401, unit=RADIANS),
        "latitude": Latitude(value=-0.2719 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2009, month=12, day=15, hour=17, minute=6, second=43)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([252.35], dtype='float32')),
    ({
        "longitude": Longitude(value=2.4578, unit=RADIANS),
        "latitude": Latitude(value=-0.3019 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2007, month=2, day=1, hour=9, minute=22, second=21)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([251.241], dtype='float32')),
    ({
        "longitude": Longitude(value=2.2841, unit=RADIANS),
        "latitude": Latitude(value=-1.3305 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2015, month=11, day=27, hour=12, minute=9, second=35)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([220.944], dtype='float32')),
    ({
        "longitude": Longitude(value=1.6576, unit=RADIANS),
        "latitude": Latitude(value=0.6586 , unit=RADIANS),
        "timestamps": DatetimeIndex([Timestamp(year=2008, month=1, day=26, hour=10, minute=12, second=34)]),
        "timezone": ZoneInfo('UTC'),
        "apply_atmospheric_refraction": True,
        "dtype": DATA_TYPE_DEFAULT,
        "array_backend": 'ARRAY_BACKEND_DEFAULT',
        "verbose": 0,
        "log": 0,
    },
     numpy_array([239.778], dtype='float32')),
]
cases_ids = [
    'Input: Latitude, Longitude:45.00-0.00_2024-6-21T12:0:0',
    'Input: Latitude, Longitude:45.00-0.00_2023-6-21T12:0:0',
    'Input: Latitude, Longitude:45.00-0.00_2022-6-21T12:0:0',
    'Input: Latitude, Longitude:45.00-0.00_2021-6-21T12:0:0',
    'Input: Latitude, Longitude:45.00-0.00_2020-6-21T12:0:0',
    'Input: Latitude, Longitude:45.00-0.00_2020-6-21T15:0:0',
    'Input: Latitude, Longitude:45.00-0.00_2020-6-21T9:0:0',
    'Input: Latitude, Longitude:45.00-0.00_2019-6-21T12:0:0',
    'Input: Latitude, Longitude:45.00-0.00_2018-6-21T12:0:0',
    'Input: Latitude, Longitude:45.00-0.00_2017-6-21T12:0:0',
    'Input: Latitude, Longitude:45.00-0.00_2016-6-21T12:0:0',
    'Input: Latitude, Longitude:45.00-0.00_2015-6-21T12:0:0',
    'Input: Latitude, Longitude:45.00-0.00_2014-6-21T12:0:0',
    'Input: Latitude, Longitude:45.00-0.00_2013-6-21T12:0:0',
    'Input: Latitude, Longitude:45.00-0.00_2012-6-21T12:0:0',
    'Input: Latitude, Longitude:45.00-0.00_2011-6-21T12:0:0',
    'Input: Latitude, Longitude:45.00-0.00_2010-6-21T12:0:0',
    'Input: Latitude, Longitude:45.00-0.00_2019-1-1T7:0:0',
    'Input: Latitude, Longitude:45.00-0.00_2019-1-1T8:0:0',
    'Input: Latitude, Longitude:45.00-0.00_2019-1-1T9:0:0',
    'Input: Latitude, Longitude:45.00-0.00_2019-1-1T10:0:0',
    'Input: Latitude, Longitude:0.00-45.00_2019-1-1T11:0:0',
    'Input: Latitude, Longitude:45.00-45.00_2019-1-1T12:0:0',
    'Input: Latitude, Longitude:45.00-45.00_2019-1-1T14:0:0',
    'Input: Latitude, Longitude:-23.03--37.31_2013-1-19T7:7:36',
    'Input: Latitude, Longitude:69.23-177.46_2010-3-3T3:45:58',
    'Input: Latitude, Longitude:-5.15--57.28_2006-3-27T13:18:15',
    'Input: Latitude, Longitude:-46.28-66.27_2019-12-7T2:21:48',
    'Input: Latitude, Longitude:-59.45--1.33_2005-4-16T15:25:49',
    'Input: Latitude, Longitude:64.79-22.75_2018-8-10T10:49:48',
    'Input: Latitude, Longitude:-44.26-159.08_2008-5-27T5:58:4',
    'Input: Latitude, Longitude:-21.40--151.61_2017-7-5T3:5:11',
    'Input: Latitude, Longitude:67.57--118.24_2005-5-17T20:15:12',
    'Input: Latitude, Longitude:-0.23-94.02_2019-12-10T9:0:31',
    'Input: Latitude, Longitude:89.63-100.53_2019-6-7T13:17:0',
    'Input: Latitude, Longitude:87.05-157.62_2011-8-18T22:25:39',
    'Input: Latitude, Longitude:21.12-168.05_2018-1-8T6:33:50',
    'Input: Latitude, Longitude:-80.12-57.08_2008-10-20T18:33:43',
    'Input: Latitude, Longitude:-51.58--27.95_2019-4-11T14:11:39',
    'Input: Latitude, Longitude:31.47--14.95_2010-4-15T20:20:8',
    'Input: Latitude, Longitude:-57.07--90.21_2020-11-4T11:42:49',
    'Input: Latitude, Longitude:-2.32--3.42_2007-10-24T8:10:38',
    'Input: Latitude, Longitude:79.09--96.45_2017-9-12T23:31:40',
    'Input: Latitude, Longitude:-50.51--140.72_2007-5-4T2:43:58',
    'Input: Latitude, Longitude:46.75-146.19_2007-12-14T5:19:59',
    'Input: Latitude, Longitude:44.30-8.93_2011-10-6T12:13:16',
    'Input: Latitude, Longitude:-63.70-56.57_2012-3-11T2:32:4',
    'Input: Latitude, Longitude:27.79--154.33_2017-7-10T2:57:42',
    'Input: Latitude, Longitude:-8.21--111.12_2018-1-22T20:47:48',
    'Input: Latitude, Longitude:-75.43-21.96_2017-6-6T13:12:13',
    'Input: Latitude, Longitude:-69.04--74.05_2009-9-19T18:31:39',
    'Input: Latitude, Longitude:88.05--102.64_2019-10-6T6:5:55',
    'Input: Latitude, Longitude:34.65-16.61_2013-7-8T18:19:56',
    'Input: Latitude, Longitude:-11.01--42.95_2010-3-28T16:20:20',
    'Input: Latitude, Longitude:33.72-10.15_2013-9-9T4:11:25',
    'Input: Latitude, Longitude:-12.72-63.62_2012-4-14T9:26:9',
    'Input: Latitude, Longitude:4.04--131.57_2008-4-6T3:23:45',
    'Input: Latitude, Longitude:41.47--49.38_2017-12-22T17:4:37',
    'Input: Latitude, Longitude:-72.91--117.49_2007-7-26T17:49:18',
    'Input: Latitude, Longitude:42.48-63.18_2010-10-21T12:56:11',
    'Input: Latitude, Longitude:-46.18--152.30_2010-6-8T3:37:47',
    'Input: Latitude, Longitude:-53.59-48.86_2013-1-12T12:54:20',
    'Input: Latitude, Longitude:-81.90--97.01_2012-1-7T6:7:6',
    'Input: Latitude, Longitude:-30.11--117.03_2009-8-24T17:47:31',
    'Input: Latitude, Longitude:27.09--85.95_2016-3-2T22:9:5',
    'Input: Latitude, Longitude:34.20--127.58_2016-10-27T2:17:21',
    'Input: Latitude, Longitude:-35.22-68.44_2020-4-11T1:30:55',
    'Input: Latitude, Longitude:-31.79-47.67_2006-9-1T13:43:45',
    'Input: Latitude, Longitude:75.61-3.37_2016-12-14T14:13:9',
    'Input: Latitude, Longitude:-7.68-129.86_2013-7-21T23:22:9',
    'Input: Latitude, Longitude:-68.23--65.12_2009-8-20T12:31:28',
    'Input: Latitude, Longitude:-72.77--32.18_2016-2-1T12:6:34',
    'Input: Latitude, Longitude:-85.88--155.07_2013-2-23T2:22:7',
    'Input: Latitude, Longitude:-14.95-139.72_2018-6-5T4:40:21',
    'Input: Latitude, Longitude:59.98-98.62_2011-4-16T13:10:22',
    'Input: Latitude, Longitude:68.36-144.88_2020-1-19T3:46:26',
    'Input: Latitude, Longitude:-3.88-116.96_2017-9-21T3:46:27',
    'Input: Latitude, Longitude:73.83--90.19_2009-9-21T8:34:12',
    'Input: Latitude, Longitude:-15.58--22.98_2009-12-15T17:6:43',
    'Input: Latitude, Longitude:-17.30-140.82_2007-2-1T9:22:21',
    'Input: Latitude, Longitude:-76.23-130.87_2015-11-27T12:9:35',
    'Input: Latitude, Longitude:37.73-94.97_2008-1-26T10:12:34',
]
