from urllib.parse import quote

from zoneinfo import ZoneInfo
from fastapi.responses import ORJSONResponse, PlainTextResponse
from pandas import DatetimeIndex
from pvgisprototype.api.quick_response_code import QuickResponseCode
from pvgisprototype.constants import FINGERPRINT_COLUMN_NAME


async def get_spectral_factor_series():
    """Calculate the spectral factor for various photovoltaic module types
    based on spectrally resolved irradiance, spectral responsivity data and a
    standardised reference spectrum.

    ## This is a placeholder Web API endpoint

    The spectral factor is the ratio of photovoltaic power generated by a solar
    module under actual conditions compared to standard reference conditions.

    Notes
    -----

    The `reference_spectrum` represents a standardised solar irradiance
    spectrum or else the expected irradiance under reference conditions. It
    defaults to the AM1.5G spectrum used for standardized testing of
    photovoltaic modules. Nonetheless, a user may define another reference
    spectrum.

    """
    # See cli/performance/spectral_effect.py
    pass

    # 1 Which spectral factor models (algorithms) to perform ?

    # 2 Read spectrally resolved irradiance data from ... a file !

    # 3 for Mihaylov or pvlib, read the average irradiance density

    # 4
    limit_spectral_range = bool()
    if limit_spectral_range:
        # See cli/performance/spectral_effect.py
        pass

    spectral_factor_series = {}
    spectral_factor_series['series'] = float()
    spectral_factor_series['components'] = {}

    # spectral_factor_series = calculate_spectral_factor(
    #     longitude=longitude,
    #     latitude=latitude,
    #     elevation=elevation,
    #     timestamps=timestamps,
    #     timezone=timezone,
    #     irradiance=spectrally_resolved_irradiance,
    #     average_irradiance_density=average_irradiance_density,
    #     responsivity=responsivity,
    #     photovoltaic_module_type=photovoltaic_module_type,
    #     reference_spectrum=reference_spectrum,
    #     integrate_reference_spectrum=integrate_reference_spectrum,
    #     spectral_factor_models=spectral_factor_model,
    #     verbose=verbose,
    #     log=log,
    #     fingerprint=fingerprint,
    # )

    csv = bool()
    if csv:
        # from pvgisprototype.web_api.utilities import generate_spectral_factor_series_csv

        in_memory_csv = str()
        # in_memory_csv = generate_spectral_factor_series_csv(
        #     dictionary=spectral_factor_series['components'],
        #     latitude=float()#latitude,
        #     longitude=float()#longitude,
        #     timestamps=DatetimeIndex()#user_requested_timestamps,
        #     timezone=ZoneInfo('UTC')#timezone,
        # )  # type: ignore
        
        # Based on https://github.com/fastapi/fastapi/discussions/9049 since file is already in memory is faster to return it as PlainTextResponse
        response = PlainTextResponse(
            content=in_memory_csv,
            headers={"Content-Disposition": f"attachment; filename={quote(csv)}"},
            media_type="text/csv"
        )

        return response
    
    # The response
    response:dict = {} # type: ignore
    SPECTRAL_FACTOR_OUTPUT_FILENAME = 'spectral_factor_series'
    headers = {
        "Content-Disposition": f'attachment; filename="{SPECTRAL_FACTOR_OUTPUT_FILENAME}.json"'
    }

    fingerprint = bool()
    if fingerprint:
        response[FINGERPRINT_COLUMN_NAME] = spectral_factor_series['components'][ # type: ignore
            FINGERPRINT_COLUMN_NAME
        ]

    quiet = bool()
    if not quiet:
        verbose = int()
        if verbose > 0:
            response = spectral_factor_series['components']
        else:
            response = {
                'Spectal Factor': spectral_factor_series['series'], 
            } # type: ignore

    metadata = bool()
    if metadata:
        response["Metadata"] = get_metadata(request=request) # type: ignore

    quick_response_code = {}
    quick_response_code['value'] = int()
    if quick_response_code['value'] != QuickResponseCode.NoneValue:
        pass

    return ORJSONResponse(response, headers=headers, media_type="application/json")
