#
# Copyright (C) 2025 European Union
#  
#  
# Licensed under the EUPL, Version 1.2 or – as soon they will be approved by the
# European Commission – subsequent versions of the EUPL (the “Licence”);
# You may not use this work except in compliance with the Licence.
# You may obtain a copy of the Licence at:
# *
# https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12 
# *
# Unless required by applicable law or agreed to in writing, software distributed under
# the Licence is distributed on an “AS IS” basis, WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied. See the Licence for the specific language
# governing permissions and limitations under the Licence.
#
from pvgisprototype.documentation.photovoltaics import A_PRIMER_ON_PHOTOVOLTAIC_PERFORMANCE


def photovoltaic_power_introduction():
    """A short introduction on photovoltaic performance"""
    introduction = """
    [underline]Photovoltaic power[/underline] is the [blue]electrical
    power[/blue] generated by a photovoltaic (PV) system when solar irradiance
    strikes its surface and is converted into electricity.

    This process relies on the [italic]photovoltaic effect[/italic], where
    solar cells convert sunlight into direct current (DC) electricity, which
    can then be used, stored, or fed into the electrical grid. The amount of
    power produced by a PV system depends on various factors such as the
    [italic]angle of sunlight[/italic], the [italic]efficiency[/italic] of the
    solar panels, environmental conditions, and the available solar irradiance.

    """

    note = """
    PVGIS can estimate the photovoltaic power output for a series of
    technologies using either [magenta]broadband[/magenta] or
    [magenta]spectrally resolved[/magenta] irradiance data.

    """
    from rich.panel import Panel

    note_in_a_panel = Panel(
        "[italic]{}[/italic]".format(note),
        title="[bold cyan]Note[/bold cyan]",
        width=78,
    )
    from rich.console import Console

    console = Console()
    # introduction.wrap(console, 30)
    console.print(introduction)
    console.print(note_in_a_panel)
    console.print(A_PRIMER_ON_PHOTOVOLTAIC_PERFORMANCE)
