import os
from math import pi
from pvgisprototype.api.irradiance.models import MethodForInexactMatches

"""
This file `constants.py` contains important hard-coded values for
`pvgisprototype`'s components.

The content is sectioned to ease-of reviewing and updating.
"""

"""
PVGIS calculates the photovoltaic power/energy production for a given location
and a solar surface. An overview of the photovoltaic performance workflow is
presented here in order to make somehow sense of the constants defined in this
module.

The flow of calculations, one step at a time, from data and input parameters to
photovoltaic power output is :

    1. position of the sun and a solar surface 
    2. incident solar irradiance
    3. conversion of the effective irradiance to photovoltaic power/energy

- Solar position

  Calculation of the solar position parameters in relation to a location and
  position of a solar surface on earth. The single most import solar angular
  measurement, in the context of a photovoltaic system, is the solar incidence
  angle. Togetehr with the solar altitude, the incidence angle impact the
  amount of in-plane irradiance as well as the temperature of the module. Both
  affect how much of the incoming solar energy is converted to electricity.

  See also `pvgis position introduction` for a detailed flow of solar timing
  and positioning.


- Solar irradiance

  Calculation of the global horizontal irradiance which is the sum of three
  components : the dirct horizontal irradiance, the sky-reflected irradiance
  and the ground-reflected irradiance. Hereafter, irradiance (i.e. _Horizontal
  irradiance_) refers to the _global_ irradiance.

- Horizontal = Normal * Altitude

- Horizontal irradiance ~~ f(solar altitude & incidence angle) ~~> In-Plane irradiance

  Note : In the context of PVGIS and throughout the source code, the _Inclined_
  irradiance is an homonym for the _In-Plane_ irradiance.

- In-Plane irradiance ~~Reflectivity Loss~~> In-Plane irradiance after reflectivity loss

  The reflectivity loss is calculated as a function of the incidence angle :
  Reflectivity Loss = f(Incidence)

- Irradiance afer reflectivity loss ~~ Spectral Effect ~~> Effective irradiance
  Spectral Effect Ratio = STC-Light ~ Sunlight
  Effective irradiance = In-Plane irradiance after Reflectivity Loss after Spectral effect

- Effective irradiance ~~Temperature & Low Irradiance effects ~~> Photovoltaic Power
  Effective irradiance = Inclined (or In-plane) Irradiance * Spectral Effect Ratio
  Photovoltaic Power = f(Effective Irradiance, Temperature, Wind Speed)

- Photovoltaic Power ~~System Loss & Degradation with age ~~> Photovoltaic Power output
  System Loss ~= 14%
"""

VERSION_FLAG_DEFAULT = False

# From end to start, the names of physical quantities and desciptipe adjectives

ENERGY_NAME = "Energy"
POWER_NAME = "Power"
IRRADIANCE_NAME = "Irradiance"
EFFECTIVE_NAME = "Effective"
GLOBAL_NAME = "Global"
DIRECT_NAME = "Direct"
DIFFUSE_NAME = "Diffuse"
REFLECTED_NAME = "Reflected"
SKY_REFLECTED = "Sky-{REFLECTED_NAME}"
GROUND_REFLECTED = "Ground-{REFLECTED_NAME}"
IN_PLANE_NAME = "In-Plane"
IN_PLANE_IRRADIANCE_NAME = f"{IN_PLANE_NAME} {IRRADIANCE_NAME}"
IN_PLANE_IRRADIANCE = IN_PLANE_IRRADIANCE_NAME
INCLINED_NAME = "Inclined"  # an homonym of IN_PLANE_NAME
INCLINED_IRRADIANCE_NAME = (
    f"{INCLINED_NAME} {IRRADIANCE_NAME}"  # an homonym of IN_PLANE_NAME
)
HORIZONTAL_NAME = "Horizontal"
NORMAL_NAME = "Normal"
SIDE_NAME = 'side'
FRONT_SIDE_NAME = f'Front-{SIDE_NAME}'
REAR_SIDE_NAME = f'Rear'#-{SIDE_NAME}'
CLEAR_SKY_NAME = 'Clear-Sky'

# Effects

TOTAL_NAME = "Total"
EFFECT_NAME = "Effect"
EFFECTS_NAME = "Effects"
NET_EFFECT = f"Net {EFFECT_NAME}"
TOTAL_EFFECT_NAME = f"{TOTAL_NAME} {EFFECT_NAME}"
TOTAL_NET_EFFECT = f"{TOTAL_NAME} Net {EFFECT_NAME}"
GAIN_NAME = "Gain"
LOSS_NAME = "Loss"
REFLECTIVITY_NAME = "Reflectivity"
SPECTRAL_NAME = "Spectral"
TEMPERATURE_AND_LOW_IRRADIANCE_NAME = "Temperature & Low Irradiance"

# Names for units

UNITLESS = "Unitless"
UNITLESSS_NAME = UNITLESS
UNIT_NAME = "Unit"
UNIT_COLUMN_NAME_PREFIX = f"{UNIT_NAME} for"
MINUTES = "minutes"
ANGLE_UNIT_NAME = "Angle " + UNIT_NAME
PERCENTAGE_NAME = "Percentage"

# Metrics

STANDARD_DEVIATION_NAME = "Standard Deviation"
ANGLE_OF_INCIDENCE_NAME = "Angle of Incidence"

# Symbols to use ?
# ⊾ ∢ ⦠ ∡ ⦛ ⦜ ⦣ ⦤ ⦥
# ⦟ # acute angle
# ⦨ ⦩ # from horizontal upwards
# ⦪ ⦫ # from horizontal downwards
# ⦮ ⦯ # from vertical upwards
# ⦬ ⦭ # from vertical downwards
# ⭍ ⌁
# ☀ ☼ 🌣 # sun
# 🗤 # rays spreading
# ⌇ # wavy line
# 🌬 # wind
# ⌖ ⯐ # position
# ⭸ ⭹

# ⍼ # Mysterious symbol !
SYMBOL_SILENCE = "🤫"
SYMBOL_SILENCE_NAME = "Quiet, Silence"

SYMBOL_CALCULATOR = "🖩"
SYMBOL_CALCULATOR_NAME = "Calculation, Analysis"

SYMBOL_INFORMATION = "🛈"
SYMBOL_INFORMATION_NAME = "Information"
SYMBOL_INTRODUCTION = SYMBOL_INFORMATION

SYMBOL_VERBOSITY = "🗣"
SYMBOL_VERBOSITY_NAME = "Verbosity"

SYMBOL_QUICK_RESPONSE = "󰐳"
SYMBOL_QUICK_RESPONSE_TETRAGRAM = "𝍌"
SYMBOL_QUICK_RESPONSE_NAME = "Quick Response Code"

SYMBOL_SUN = "☉"
SYMBOL_SUN_NAME = "Sun"

SYMBOL_SILICON = "Si"
SYMBOL_SILICON_NAME = "Silicon"

SYMBOL_ENERGY = "🔌"  # ⌁
ENERGY_NAME_WITH_SYMBOL = f"{ENERGY_NAME} {SYMBOL_ENERGY}"
SYMBOL_ENERGY_NAME = f"{ENERGY_NAME}"
SYMBOL_UNIT_ENERGY = ""

SYMBOL_POWER = "⌁"
SYMBOL_POWER_NAME = f"{POWER_NAME}"

SYMBOL_IRRADIANCE = "⸾"  # ⌇
SYMBOL_IRRADIANCE_NAME = f"{IRRADIANCE_NAME}"

SYMBOL_BROADBAND_IRRADIANCE = SYMBOL_IRRADIANCE

SYMBOL_SPECTRALLY_RESOLVED_IRRADIANCE = "󱩅"

SYMBOL_LIMITS_OPEN = "["
SYMBOL_LIMITS_CLOSE = "]"
SYMBOL_IRRADIANCE_LIMITS = (
    f"{SYMBOL_LIMITS_OPEN}{SYMBOL_IRRADIANCE}{SYMBOL_LIMITS_CLOSE}"
)

SYMBOL_DIRECT = "⇣"
SYMBOL_DIRECT_NAME = f"{DIRECT_NAME}"

SYMBOL_EFFECTIVE = "⭍"
SYMBOL_EFFECTIVE_NAME = f"{EFFECTIVE_NAME}"

SYMBOL_INCLINED = "∡"
SYMBOL_INCLINED_NAME = f"{INCLINED_NAME}"

SYMBOL_IN_PLANE = SYMBOL_INCLINED  # Homonyms
SYMBOL_IN_PLANE_NAME = f"{IN_PLANE_NAME}"

SYMBOL_HORIZONTAL = "⭳"  # ⤓
SYMBOL_HORIZONTAL_NAME = f"{HORIZONTAL_NAME}"

SYMBOL_NORMAL = "⦜"
SYMBOL_NORMAL_NAME = f"{NORMAL_NAME}"

SYMBOL_CLEAR_SKY = "🌣"  # ☼ ☀
SYMBOL_CLEAR_SKY_NAME = f"{CLEAR_SKY_NAME}"

SYMBOL_DIFFUSE = "🗤"  # ↯ 🗤
SYMBOL_DIFFUSE_IRRADIANCE_NAME = f"{DIFFUSE_NAME}"

SYMBOL_REFLECTED = "⭞"  # ☈ ☇ ⭚ ∡ ⭛
SYMBOL_REFLECTED_IRRADIANCE_NAME = f"{REFLECTED_NAME}"

SYMBOL_LONGITUDE = "ϑ"
SYMBOL_LONGITUDE_NAME = "Longitude"

SYMBOL_LATITUDE = "ϕ"
SYMBOL_LATITUDE_NAME = "Latitude"

ELEVATION_NAME = "Elevation"
SYMBOL_ELEVATION = "🏔"
SYMBOL_ELEVATION_NAME = f"{ELEVATION_NAME}"
SYMBOL_UNIT_ELEVATION = "m"
SYMBOL_UNIT_ELEVATION_LONG = "meters"

SYMBOL_ORIENTATION = "↻"  # "🧭"
SYMBOL_ORIENTATION_NAME = "Orientation"

SYMBOL_ADJUSTED = "′"
SYMBOL_ADJUSTED_NAME = "Prime"  # Adjusted

SYMBOL_TIMING = "⏲"
SYMBOL_TIMING_NAME = "Timing"

SMYBOL_TIMESTAMP = "📅"
SMYBOL_TIMESTAMP_NAME = "Timestamp"

SYMBOL_PERIODS = "⨉"
SYMBOL_PERIODS_NAME = "Periods"

SYMBOL_DECLINATION = "∢"
SYMBOL_DECLINATION_NAME = "Declination"

SYMBOL_HOUR_ANGLE = "󱩷"  # 🕛
SYMBOL_HOUR_ANGLE_NAME = "Hour angle"

SYMBOL_START_TIME = "⏳"
SYMBOL_START_TIME_NAME = "Start time"

SYMBOL_END_TIME = "⌛"
SYMBOL_END_TIME_NAME = "End time"

SYMBOL_FREQUENCY = "⏱"  # ∿'  #🔄'
SYMBOL_FREQUENCY_NAME = "Frequency"

SYMBOL_SUNRISE = "🌅"  # ?
SYMBOL_SUNRISE_NAME = "Sunrise"

SYMBOL_ZENITH = "⦭"
SYMBOL_ZENITH_NAME = "Zenith"

SYMBOL_ALTITUDE = "⦩"
SYMBOL_ALTITUDE_NAME = "Altitude"

SYMBOL_AZIMUTH = "󱦥"  # ⭮ ⦬
SYMBOL_AZIMUTH_NAME = "Azimuth"

SYMBOL_AZIMUTH_DIFFERENCE = "Δ⭮"  # ⦬
SYMBOL_AZIMUTH_DIFFERENCE_NAME = "Azimuth difference"

SYMBOL_POSITIONING = "⯐"
SYMBOL_POSITIONING_NAME = "Positioning"

SYMBOL_TILT = "∡"
SYMBOL_TILT_NAME = "Tilt"

SYMBOL_INCIDENCE = "⭸"  # ⦡
SYMBOL_INCIDENCE_NAME = "Incidence"

SYMBOL_HORIZON = "⛰"
SYMBOL_HORIZON_NAME = "Horizon"

SYMBOL_VISIBLE = "👁"
SYMBOL_VISIBLE_NAME = "Visible"

SYMBOL_SHADING = '🮞'
SYMBOL_SHADING_NAME = 'Shading'

SYMBOL_TEMPERATURE = "🌡"
TEMPERATURE_NAME = "Temperature"
SYMBOL_TEMPERATURE_NAME = f"{TEMPERATURE_NAME}"
SYMBOL_UNIT_TEMPERATURE = "℃"

SYMBOL_WIND_SPEED = "🌬"
SYMBOL_WIND_SPEED_NAME = "Wind Speed"
SYMBOL_UNIT_WIND_SPEED = "㎧"

SYMBOL_FINGERPRINT = "🆔"  # 
SYMBOL_FINGERPRINT_NAME = "Fingerprint"

SYMBOL_RADIANS = "㎭"
RADIANS = "radians"
SYMBOL_RADIANS_NAME = RADIANS

SYMBOL_DEGREES = "°"
DEGREES = "degrees"
SYMBOL_DEGREES_NAME = DEGREES

SYMBOL_UNIT_AU = "㍳"

SYMBOL_LETTER_F = "𝑓()"
SYMBOL_LETTER_F_NAME = "Function, Model/ling, Algorithm"

SYMBOL_SUMMATION = "⅀"
SYMBOL_SUMMATION_NAME = "N-ary Summation"

SYMBOL_MEAN = "μ"
SYMBOL_MEAN_NAME = "Mean"

SYMBOL_RATIO = "∶"
SYMBOL_RATIO_NAME = "Ratio"

SYMBOL_PROPORTIONAL_TO = "∝"
SYMBOL_PROPORTIONAL_TO_NAME = "Proportionality factor"

SYMBOL_PERCENTAGE = "％"
SYMBOL_PERCENTAGE_NAME = "Percentage"

SYMBOL_EFFICIENCY = f"{SYMBOL_PERCENTAGE}"
SYMBOL_EFFICIENCY_NAME = "Efficiency"

SYMBOL_PLUS_MINUS = "±"
SYMBOL_PLUS_MINUS_NAME = "Plus Minus"

SYMBOL_SYMMETRIC_DIFFERENCE = "⊖"
SYMBOL_SYMMETRIC_DIFFERENCE_NAME = "Exclusion" # here use for out-of-range values !

SYMBOL_LOSS = "-"
SYMBOL_LOSS_NAME = "Loss"

SYMBOL_REFLECTIVITY = "⭜"  # ☇
SYMBOL_REFLECTIVITY_NAME = "Reflectivity"

SYMBOL_CHART_CURVE = "󰱐"
SYMBOL_CHART_CURVE_NAME = "Time series"

SYMBOL_PLOT = "📈"
SYMBOL_PLOT_NAME = "Plot"

SYMBOL_UNIPLOT = f"{SYMBOL_PLOT}"
SYMBOL_UNIPLOT_NAME = "Uniplot"

SYMBOL_FILTER = ""
SYMBOL_SELECT = SYMBOL_FILTER
SYMBOL_FILTER_NAME = "Filter"

SYMBOL_GROUP = "󰾂"
SYMBOL_GROUP_NAME = "Group"

SYMBOL_DESCRIPTIONS = {
    SYMBOL_SILENCE: SYMBOL_SILENCE_NAME,
    SYMBOL_CALCULATOR: SYMBOL_CALCULATOR_NAME,
    SYMBOL_POWER: SYMBOL_POWER_NAME,
    SYMBOL_IRRADIANCE: SYMBOL_IRRADIANCE_NAME,
    SYMBOL_EFFECTIVE: SYMBOL_EFFECTIVE_NAME,
    SYMBOL_LOSS: SYMBOL_LOSS_NAME,
    SYMBOL_INCLINED: SYMBOL_INCLINED_NAME,
    SYMBOL_REFLECTIVITY: SYMBOL_REFLECTIVITY_NAME,
    SYMBOL_HORIZONTAL: SYMBOL_HORIZONTAL_NAME,
    SYMBOL_NORMAL: SYMBOL_NORMAL_NAME,
    SYMBOL_CLEAR_SKY: SYMBOL_CLEAR_SKY_NAME,
    SYMBOL_DIFFUSE: SYMBOL_DIFFUSE_IRRADIANCE_NAME,
    SYMBOL_REFLECTED: SYMBOL_REFLECTED_IRRADIANCE_NAME,
    SYMBOL_TEMPERATURE: SYMBOL_TEMPERATURE_NAME,
    SYMBOL_WIND_SPEED: SYMBOL_WIND_SPEED_NAME,
    SYMBOL_LONGITUDE: SYMBOL_LONGITUDE_NAME,
    SYMBOL_LATITUDE: SYMBOL_LATITUDE_NAME,
    SYMBOL_TIMING: SYMBOL_TIMING_NAME,
    SYMBOL_FREQUENCY: SYMBOL_FREQUENCY_NAME,
    SYMBOL_DEGREES: SYMBOL_DEGREES_NAME,
    SYMBOL_RADIANS: SYMBOL_RADIANS_NAME,
    SYMBOL_DECLINATION: SYMBOL_DECLINATION_NAME,
    SYMBOL_HOUR_ANGLE: SYMBOL_HOUR_ANGLE_NAME,
    SYMBOL_ZENITH: SYMBOL_ZENITH_NAME,
    SYMBOL_ALTITUDE: SYMBOL_ALTITUDE_NAME,
    SYMBOL_AZIMUTH: SYMBOL_AZIMUTH_NAME,
    SYMBOL_POSITIONING: SYMBOL_POSITIONING_NAME,
    SYMBOL_HORIZON: SYMBOL_HORIZON_NAME,
    SYMBOL_ORIENTATION: SYMBOL_ORIENTATION_NAME,
    SYMBOL_TILT: SYMBOL_TILT_NAME,
    SYMBOL_INCIDENCE: SYMBOL_INCIDENCE_NAME,
    SYMBOL_VISIBLE: SYMBOL_VISIBLE_NAME,
    SYMBOL_SUNRISE: SYMBOL_SUNRISE_NAME,
    SYMBOL_SHADING: SYMBOL_SHADING_NAME,
    SYMBOL_ADJUSTED: SYMBOL_ADJUSTED_NAME,
    SYMBOL_FINGERPRINT: SYMBOL_FINGERPRINT_NAME,
    SYMBOL_SUMMATION: SYMBOL_SUMMATION_NAME,
    SYMBOL_MEAN: SYMBOL_MEAN_NAME,
    SYMBOL_RATIO: SYMBOL_RATIO_NAME,
    SYMBOL_PROPORTIONAL_TO: SYMBOL_PROPORTIONAL_TO_NAME,
    SYMBOL_PERCENTAGE: SYMBOL_PERCENTAGE_NAME,
    SYMBOL_GROUP: SYMBOL_GROUP_NAME,
}

SYMBOL_GROUPS_DESCRIPTIONS = {
    "Basic": {
        SYMBOL_GROUP: SYMBOL_GROUP_NAME,
    },
    "Operations": {
        SYMBOL_CALCULATOR: SYMBOL_CALCULATOR_NAME,
        SYMBOL_ADJUSTED: SYMBOL_ADJUSTED_NAME,
        SYMBOL_SUMMATION: SYMBOL_SUMMATION_NAME,
        SYMBOL_RATIO: SYMBOL_RATIO_NAME,
        SYMBOL_PROPORTIONAL_TO: SYMBOL_PROPORTIONAL_TO_NAME,
        SYMBOL_PERCENTAGE: SYMBOL_PERCENTAGE_NAME,
    },
    "Features": {
        SYMBOL_SILENCE: SYMBOL_SILENCE_NAME,
        SYMBOL_FINGERPRINT: SYMBOL_FINGERPRINT_NAME,
    },
    "Units": {
        SYMBOL_DEGREES: SYMBOL_DEGREES_NAME,
        SYMBOL_RADIANS: SYMBOL_RADIANS_NAME,
    },
    "Timestamps": {
        SYMBOL_FREQUENCY: SYMBOL_FREQUENCY_NAME,
    },
    "Solar Power/Energy": {
        SYMBOL_POWER: SYMBOL_POWER_NAME,
        SYMBOL_LOSS: SYMBOL_LOSS_NAME,
    },
    "Solar Irradiance": {
        SYMBOL_IRRADIANCE: SYMBOL_IRRADIANCE_NAME,
        SYMBOL_INCLINED: SYMBOL_INCLINED_NAME,
        SYMBOL_REFLECTIVITY: SYMBOL_REFLECTIVITY_NAME,
        SYMBOL_EFFECTIVE: SYMBOL_EFFECTIVE_NAME,
        SYMBOL_HORIZONTAL: SYMBOL_HORIZONTAL_NAME,
        SYMBOL_NORMAL: SYMBOL_NORMAL_NAME,
        SYMBOL_CLEAR_SKY: SYMBOL_CLEAR_SKY_NAME,
        SYMBOL_DIFFUSE: SYMBOL_DIFFUSE_IRRADIANCE_NAME,
        SYMBOL_REFLECTED: SYMBOL_REFLECTED_IRRADIANCE_NAME,
    },
    "Meteorological Variables": {
        SYMBOL_TEMPERATURE: SYMBOL_TEMPERATURE_NAME,
        SYMBOL_WIND_SPEED: SYMBOL_WIND_SPEED_NAME,
    },
    "Solar Position": {
        SYMBOL_TIMING: SYMBOL_TIMING_NAME,
        SYMBOL_POSITIONING: SYMBOL_POSITIONING_NAME,
        SYMBOL_DECLINATION: SYMBOL_DECLINATION_NAME,
        SYMBOL_HOUR_ANGLE: SYMBOL_HOUR_ANGLE_NAME,
        SYMBOL_ZENITH: SYMBOL_ZENITH_NAME,
        SYMBOL_ALTITUDE: SYMBOL_ALTITUDE_NAME,
        SYMBOL_AZIMUTH: SYMBOL_AZIMUTH_NAME,
        SYMBOL_INCIDENCE: SYMBOL_INCIDENCE_NAME,
        SYMBOL_VISIBLE: SYMBOL_VISIBLE_NAME,
        SYMBOL_SHADING: SYMBOL_SHADING_NAME,
    },
    "Solar Surface": {
        SYMBOL_LONGITUDE: SYMBOL_LONGITUDE_NAME,
        SYMBOL_LATITUDE: SYMBOL_LATITUDE_NAME,
        SYMBOL_ORIENTATION: SYMBOL_ORIENTATION_NAME,
        SYMBOL_TILT: SYMBOL_TILT_NAME,
    },
}

METADATA_FLAG_DEFAULT = False
COMMAND_METADATA_DESCRIPTION = "Command metadata"

DATA_TYPE_DEFAULT = "float32"  # takes halve of the time to process than float64
DATA_TYPE_DESCRIPTION = f"Data type for (array) calculations, default is `{DATA_TYPE_DEFAULT}`."  # takes halve of the time to process than float64
ARRAY_BACKEND_DEFAULT = "numpy"  # OR 'CUPY', 'DASK'
ARRAY_BACKEND_DESCRIPTION = f"Backend for (array) calculations, default is {ARRAY_BACKEND_DEFAULT}."  # OR 'CUPY', 'DASK'
MULTI_THREAD_FLAG_DEFAULT = True
MULTI_THREAD_FLAG_DESCRIPTION = f"Perform calculations in a multi-thread context, default is {MULTI_THREAD_FLAG_DEFAULT}."

VERBOSE_LEVEL_DEFAULT = 0
VERBOSE_LEVEL_DESCRIPTION = f"{SYMBOL_VERBOSITY} Verbosity level : 0 returns list of values only, higher levels reveal intermediate calculations."
VERBOSE_LEVEL_MULTI_MODULE_DEFAULT = 9

QUIET_FLAG_DEFAULT = False
QUIET_FLAG_DESCRIPTION = f"{SYMBOL_SILENCE} Silence output, useful for timing the duration of processes or partial output"

LOG_LEVEL_DEFAULT = 0
LOG_LEVEL_DESCRIPTION = "Log level"

cPROFILE_FLAG_DEFAULT = False
cPROFILE_FLAG_DESCRIPTION = "Profiling"

HASH_AFTER_THIS_VERBOSITY_LEVEL = 6
DEBUG_AFTER_THIS_VERBOSITY_LEVEL = 10

VALIDATE_OUTPUT_DEFAULT = False

ROUNDING_PLACES_DEFAULT = 3
ROUNDING_PLACES_DESCRIPTION = (
    f"Number of decimal places for rounding (default is {ROUNDING_PLACES_DEFAULT})"
)

TOLERANCE_DEFAULT = 0.1  # Is this a sane default ?
TOLERANCE_MINIMUM = 0.1
FIX_OUT_OF_RANGE_VALUES_POSITIVE = 0.99999
FIX_OUT_OF_RANGE_VALUES_NEGATIVE = -0.99999


# Time

TIMESTAMP_NAME = "Timestamp"
TIMESTAMP_DESCRIPTION = (
    "Date-timestamp of data to extract from series, ex. '2112-12-21 21:12:12'"
)
TIMESTAMPS_DESCRIPTION = f"{SYMBOL_TIMING} Specific comma-separated date-timestamp/s of data to extract from time series, ex. `2112-12-21`, `2112-12-21 12:21:21`, `2112-12-21 21:12:12`"

TIME_SERIES_DESCRIPTION = "A time series dataset (any format supported by Xarray)"
INEXACT_MATCHES_METHOD_DESCRIPTION = "Method for nearest neighbor (inexact) lookups. Read Xarray manual on nearest-neighbor-lookups"
NEAREST_NEIGHBOR_LOOKUP_DESCRIPTION = "Enable nearest neighbor (inexact) lookups. Read Xarray manual on nearest-neighbor-lookups"
TOLERANCE_DESCRIPTION = "Maximum distance between original & new labels for inexact matches. Read Xarray manual on nearest-neighbor-lookups"
MASK_AND_SCALE_DESCRIPTION = "Mask and scale the series"
IN_MEMORY_DESCRIPTION = "Whether to process data in memory"

START_NAME = "Start"
START_TIME_DESCRIPTION = f"{SYMBOL_START_TIME} {START_NAME} {TIMESTAMP_NAME}. **Attention**: if not given, the defaul time is `00:00:00`."

PERIODS_NAME = "Periods"
PERIODS_DESCRIPTION = f"{SYMBOL_PERIODS} Number of {PERIODS_NAME} to generate. Can be used with _either_ `start_time` _or_ `end_time` plus the frequency, or then _both_ start _and_ end time which will generate automatically the frequency (linearly spaced)."
FREQUENCY_DESCRIPTION = f"{SYMBOL_FREQUENCY} Frequency for the generation of timestamps given _either_ 1) a `start_time` and `end_time` _or_ 2) `start_time` plus `periods` _or 3) `end_time` plus the `periods`. See also relevant notes in Pandas documentation."
END_NAME = "End"
END_TIME_DESCRIPTION = f"{SYMBOL_END_TIME} {END_NAME} {TIMESTAMP_NAME} **Attention**: if not given, the defaul time is `00:00:00`."

TIMEZONE_NAME = "Timezone"
TIMEZONE_DESCRIPTION = f"{TIMEZONE_NAME} (ex. 'UTC') supported by [the IANA Time Zone Database](https://www.iana.org/time-zones). See [list of valid IANA time zone (TZ) identifiers](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List)."
TIMEZONE_UTC = "UTC"
TIMEZONE_DEFAULT = None

LOCAL_TIME_DESCRIPTION = "Use the system's local time zone"

RANDOM_TIME_DESCRIPTION = "Generate a random date, time, and timezone"
RANDOM_DAY_DESCRIPTION = "Generate a random day"
RANDOM_DAYS_DESCRIPTION = "Generate random days"

ANNUAL_NAME = "Annual"
MONTHLY_NAME = "Monthly"
DAILY_NAME = "Daily"


# Units

UNITLESSS_COLUMN_NAME = UNITLESS + " Column"
UNITS_COLUMN_NAME = UNIT_NAME
TIME_OUTPUT_UNITS_DEFAULT = MINUTES
TIME_UNITS_COLUMN_NAME = "Time " + UNIT_NAME
TIMESTAMPS_FREQUENCY_DEFAULT = "h"  # hours

ANGLE_OUTPUT_UNITS_DEFAULT = RADIANS
ANGLE_UNITS_COLUMN_NAME = ANGLE_UNIT_NAME
ANGLE_OUTPUT_UNITS_DESCRIPTION = "Output units for angles"

IN_MEMORY_FLAG_DEFAULT = False
MASK_AND_SCALE_FLAG_DEFAULT = False

NEIGHBOR_LOOKUP_DEFAULT = MethodForInexactMatches.nearest

TERMINAL_WIDTH_FRACTION = 0.9
TERMINAL_WIDTH_FRACTION_DESCRIPTION = "Terminal width for Uniplot"

LATITUDE_MINIMUM = -90
LATITUDE_MAXIMUM = 90  # in PVGIS : rowoffset
LONGITUDE_MINIMUM = -180
LONGITUDE_MAXIMUM = 180  # in PVGIS : coloffset
ELEVATION_MINIMUM = 0
ELEVATION_MAXIMUM = 8848
HORIZON_HEIGHT_UNIT = "degrees"
SOLAR_DECLINATION_MINIMUM = 0
SOLAR_DECLINATION_MAXIMUM = 90

SURFACE_TILT_MINIMUM = 0
# SURFACE_TILT_MAXIMUM = 90
SURFACE_TILT_MAXIMUM = 180
SURFACE_TILT_DEFAULT = 45  # degrees
SURFACE_TILT_HORIZONTALLY_FLAT_PANEL_THRESHOLD = 0.0001
OPTIMISE_SURFACE_TILT_FLAG_DEFAULT = False
OPTIMISE_SURFACE_GEOMETRY_FLAG_DEFAULT = False
SURFACE_ORIENTATION_MINIMUM = 0
SURFACE_ORIENTATION_MAXIMUM = 360
SURFACE_ORIENTATION_DEFAULT = 180  # Due south, counting from North
OPTIMISE_SURFACE_POSITION_DESCRIPTION = "Optimise surface position"
WORKERS_FOR_SURFACE_POSITION_OPTIMIZATION = int(os.cpu_count() / 2) # NOTE WE HAVE TO REVIEW THIS. Currenly, we are using half of the available CPUS for doing this calculations!!!
NUMBER_OF_SAMPLING_POINTS_SURFACE_POSITION_OPTIMIZATION = 100 # NOTE This by default was 100 (higher result accuracy) but for being fast we can use 15 but the result will be less precise
NUMBER_OF_SAMPLING_POINTS_SURFACE_POSITION_OPTIMIZATION_DESCRIPTION = "Number of sampling points used in the construction of the simplicial complex.  Use a low number (e.g., 15) for faster but less accurate optimization results. For more information read [here](https://docs.scipy.org/doc/scipy-1.15.0/reference/generated/scipy.optimize.shgo.html#scipy.optimize.shgo)."
NUMBER_OF_SAMPLING_POINTS_SURFACE_POSITION_OPTIMIZATION_MAXIMUM = 2000
NUMBER_OF_SAMPLING_POINTS_SURFACE_POSITION_OPTIMIZATION_MINIMUM = 15
SAMPLING_METHOD_DESCRIPTION = "Sampling method for optimiser SHGO"
NUMBER_OF_ITERATIONS_DEFAULT = 20
NUMBER_OF_ITERATIONS_DESCRIPTION = "Number of iterations used in the construction of the simplicial complex. Use a low number (e.g., 1) for faster but less accurate optimization results. For more information read [here](https://docs.scipy.org/doc/scipy-1.15.0/reference/generated/scipy.optimize.shgo.html#scipy.optimize.shgo)."
NUMBER_OF_ITERATIONS_MINIMUM = 1
OPTIMISER_PRECISION_GOAL = 0.1
OPTIMISER_GRADIENT_TOLERANCE = 0.1

SOLAR_CONSTANT_MINIMUM = 1360
SOLAR_CONSTANT = 1360.8  # at mean Earth-Sun distance in W/m^2
SOLAR_CONSTANT_TOLERANCE = 0.5
SOLAR_CONSTANT_COLUMN_NAME = "Solar constant"
SOLAR_CONSTANT_DESCRIPTION = "Solar constant"

AU = 1  # Earth-Sun distance in Astronomical Units
AU_UNIT = f"{SYMBOL_UNIT_AU}"
STEPHAN_BOLTZMANN_CONSTANT = 5.67e-8  # in W/m^2 K^4
EXTRATERRESTRIAL_IRRADIANCE_MIN = 1315  # 1315.2963089821737 for days_in_a_year = 365.25
EXTRATERRESTRIAL_IRRADIANCE_MAX = 1407  # 1406.3049813983132 for days_in_a_year = 365.25

RANDOM_DAY_FLAG_DEFAULT = False
RANDOM_DAY_SERIES_FLAG_DEFAULT = False
RANDOM_TIMESTAMPS_FLAG_DEFAULT = False
FRACTIONAL_YEAR_MINIMUM = 0

FRACTIONAL_YEAR_MAXIMUM = 2 * pi
DAY_OF_YEAR_COLUMN_NAME = "Day of year"

PERIGEE_OFFSET = 0.048869
PERIGEE_OFFSET_COLUMN_NAME = "Perigee"
PERIGEE_OFFSET_DESCRIPTION = "Perigee offset"

ECCENTRICITY_CORRECTION_FACTOR = 0.03344  # 0.01672
ECCENTRICITY_CORRECTION_FACTOR_COLUMN_NAME = "Eccentricity"
ECCENTRICITY_CORRECTION_DESCRIPTION = "Eccentricity correction factor"

DAY_ANGLE_SERIES = "Day angle"
DISTANCE_CORRECTION_COLUMN_NAME = "Distance correction"

TERM_N_IN_SHADE = 0.25227
TERM_N_NAME = "term N"
TERM_N_COLUMN_NAME = f"{TERM_N_NAME} {SYMBOL_PROPORTIONAL_TO}"
KB_RATIO_NAME = "Kb"
KB_RATIO_COLUMN_NAME = f"{KB_RATIO_NAME} {SYMBOL_RATIO}"

LINKE_TURBIDITY_MINIMUM = 0
LINKE_TURBIDITY_MAXIMUM = 8
LINKE_TURBIDITY_DEFAULT = 2  # to get going for now
LINKE_TURBIDITY_TIME_SERIES_DEFAULT = LINKE_TURBIDITY_DEFAULT  # to get going for now
LINKE_TURBIDITY_UNIT = UNITLESS
LINKE_NAME = "Linke"
LINKE_TURBIDITY_COLUMN_NAME = LINKE_NAME
LINKE_TURBIDITY_ADJUSTED_COLUMN_NAME = (
    f"{LINKE_TURBIDITY_COLUMN_NAME} {SYMBOL_ADJUSTED}"
)
LINKE_TURBIDITY_DESCRIPTION = "Linke turbidity factor"

OPTICAL_AIR_MASS_DEFAULT = 2
OPTICAL_AIR_MASS_TIME_SERIES_DEFAULT = OPTICAL_AIR_MASS_DEFAULT
OPTICAL_AIR_MASS_UNIT = UNITLESS
OPTICAL_AIR_MASS_COLUMN_NAME = "Air mass"
RAYLEIGH_OPTICAL_THICKNESS_COLUMN_NAME = "Rayleigh"
RAYLEIGH_OPTICAL_THICKNESS_UNIT = UNITLESS
ATMOSPHERIC_REFRACTION_FLAG_DEFAULT = True
ATMOSPHERIC_REFRACTION_DESCRIPTION = "Apply atmospheric refraction correction"

REFRACTED_SOLAR_ZENITH_ANGLE_DEFAULT = 1.5853349194640094  # radians
REFRACTED_SOLAR_ZENITH_DESCRIPTION = "Refracted solar zenith angle"
REFRACTED_SOLAR_ZENITH_DESCRIPTION_IN_DEGREES = f"{REFRACTED_SOLAR_ZENITH_DESCRIPTION} in decimal {DEGREES}{SYMBOL_DEGREES}"
REFRACTED_SOLAR_ALTITUDE_COLUMN_NAME = "Refracted alt."

TIME_OFFSET_GLOBAL_DEFAULT = 0
TIME_OFFSET_GLOBAL_DESCRIPTION = "Global time offset in hours"

HOUR_OFFSET_DEFAULT = 0
HOUR_OFFSET_DESCRIPTION = "Hour offset"

NO_SOLAR_INCIDENCE = 0  # Solar incidence when shadow is detected

TEMPERATURE_DEFAULT = 14  # global average surface air temperature, Celsius degrees
TEMPERATURE_AT_STANDARD_TEST_CONDITIONS = (
    25  # Cell temperature under standard test conditions, Celsius degrees
)
TEMPERATURE_COLUMN_NAME = f"{TEMPERATURE_NAME} {SYMBOL_UNIT_TEMPERATURE}"  #
TEMPERATURE_TIME_SERIES_DESCRIPTION = f"{TEMPERATURE_NAME} series"
TEMPERATURE_ADJUSTED_COLUMN_NAME = f"{TEMPERATURE_NAME}′ {SYMBOL_UNIT_TEMPERATURE}"
TEMPERATURE_DEVIATION_COLUMN_NAME = f"{TEMPERATURE_NAME} ≏{SYMBOL_UNIT_TEMPERATURE}"  # for the PV module's temperature model

WIND_SPEED_DEFAULT = 0
WIND_NAME = "Wind"
SPEED_NAME = "Speed"
WIND_SPEED_NAME = f"{WIND_NAME} {SPEED_NAME}"
WIND_SPEED_COLUMN_NAME = f"{WIND_SPEED_NAME} {SYMBOL_UNIT_WIND_SPEED}"
WIND_SPEED_TIME_SERIES_DESCRIPTION = f"{WIND_SPEED_NAME} series"

ALBEDO_DEFAULT = 0.2
ALBEDO_MAXIMUM = 1
ALBEDO_MINIMUM = 0
ALBEDO_COLUMN_NAME = "Albedo"

ALBEDO_MINIMUM = 0.0
ALBEDO_MAXIMUM = 1.0
ALBEDO_DESCRIPTION = "Albedo value for the surface"


PHOTOVOLTAIC_NAME = "Photovoltaic"
PHOTOVOLTAIC_SHORTNAME = "PV"
MODULE_NAME = 'Module'
TYPE_NAME = 'Type'
PHOTOVOLTAIC_MODULE_TYPE_NAME = f"{PHOTOVOLTAIC_NAME} {MODULE_NAME} {TYPE_NAME}"
TECHNOLOGY_NAME = "Technology"
PHOTOVOLTAIC_MODULE_TECHNOLOGY = f"{PHOTOVOLTAIC_NAME} {MODULE_NAME} {TECHNOLOGY_NAME}"
PHOTOVOLTAIC_MODULE_DEFAULT = "cSi:Free standing"
PHOTOVOLTAIC_MODULE_DESCRIPTION = (
    f"{SYMBOL_SILICON} Photovoltaic module technology and mount type"
)

PHOTOVOLTAIC_POWER_OUTPUT_FILENAME = "photovoltaic_power_time_series"
PHOTOVOLTAIC_PERFORMANCE_COLUMN_NAME = "Photovoltaic Performance"
PHOTOVOLTAIC_PERFORMANCE_ANALYSIS_OUTPUT_FILENAME = "photovoltaic_performance_analysis"

# Efficiency : Gain & Loss

EFFICIENCY_FACTOR_DEFAULT = None
REAR_SIDE_EFFICIENCY_FACTOR_DEFAULT = 0.2
EFFICIENCY_FACTOR_MINIMUM = 0
EFFICIENCY_FACTOR_MAXIMUM = 1
EFFICIENCY_NAME = "Efficiency"
FACTOR_NAME = "Factor"
EFFICIENCY_FACTOR_NAME = f"{EFFICIENCY_NAME} {FACTOR_NAME.lower()}"
EFFICIENCY_COLUMN_NAME = f"{EFFICIENCY_NAME} %"
REAR_SIDE_EFFICIENCY_COLUMN_NAME = f"{REAR_SIDE_NAME} {EFFICIENCY_COLUMN_NAME}"
EFFICIENCY_DESCRIPTION = f"{EFFICIENCY_NAME} value"

EFFICIENCY_FACTOR_COLUMN_NAME = f"{EFFICIENCY_FACTOR_NAME} %"
EFFICIENCY_FACTOR_DESCRIPTION = f"{EFFICIENCY_FACTOR_NAME} from irradiance to power"

LOSS_DEFAULT = None
LOSS_NAME = "Loss"
LOSS_COLUMN_NAME = f"{LOSS_NAME} {SYMBOL_LOSS}"
LOSS_FACTOR_COLUMN_NAME = f"{LOSS_NAME} {FACTOR_NAME} %"

# System

SYSTEM_NAME = "System"

SYSTEM_EFFICIENCY_DEFAULT = 0.86  # systemEfficiency_global = 1.0  # from PVGIS v5.2
SYSTEM_EFFICIENCY_MINIMUM = 0
SYSTEM_EFFICIENCY_MAXIMUM = 1
SYSTEM_EFFICIENCY = f"{SYSTEM_NAME} {EFFICIENCY_NAME}"
SYSTEM_EFFICIENCY_COLUMN_NAME = f"{SYSTEM_NAME} {EFFICIENCY_NAME} %"
SYSTEM_EFFICIENCY_DESCRIPTION = f"{SYMBOL_EFFICIENCY} {SYSTEM_NAME} {EFFICIENCY_NAME}"
TOTAL_SYSTEM_EFFICIENCY_EFFECT_COLUMN_NAME = (
    f"{TOTAL_NAME} {SYSTEM_EFFICIENCY_COLUMN_NAME}"
)
UNIT_FOR_TOTAL_SYSTEM_EFFICIENCY_EFFECT_COLUMN_NAME = (
    f"{UNIT_COLUMN_NAME_PREFIX} {TOTAL_SYSTEM_EFFICIENCY_EFFECT_COLUMN_NAME}"
)
MEAN_SYSTEM_EFFICIENCY_EFFECT_COLUMN_NAME = f"Mean {SYSTEM_EFFICIENCY_COLUMN_NAME}"
UNIT_FOR_MEAN_SYSTEM_EFFICIENCY_EFFECT_COLUMN_NAME = (
    f"{UNIT_COLUMN_NAME_PREFIX} {MEAN_SYSTEM_EFFICIENCY_EFFECT_COLUMN_NAME}"
)
SYSTEM_EFFICIENCY_EFFECT_PERCENTAGE_COLUMN_NAME = (
    f"{SYSTEM_EFFICIENCY_COLUMN_NAME} {SYMBOL_PERCENTAGE}"
)

SYSTEM_LOSS_DEFAULT = 1 - SYSTEM_EFFICIENCY_DEFAULT
SYSTEM_LOSS = f"{SYSTEM_NAME} {LOSS_NAME}"
SYSTEM_LOSS_COLUMN_NAME = f"{SYSTEM_NAME} {LOSS_NAME} %"
SYSTEM_LOSS_DESCRIPTION = f"{SYSTEM_LOSS} & Degradation with age"

# System - Rear side

REAR_SIDE_SYSTEM_NAME = "System"

REAR_SIDE_SYSTEM_EFFICIENCY_DEFAULT = 0.20  # systemEfficiency_global = 1.0  # from PVGIS v5.2
REAR_SIDE_SYSTEM_EFFICIENCY_MINIMUM = 0
REAR_SIDE_SYSTEM_EFFICIENCY_MAXIMUM = 1
REAR_SIDE_SYSTEM_EFFICIENCY = f"{REAR_SIDE_SYSTEM_NAME} {EFFICIENCY_NAME}"
REAR_SIDE_SYSTEM_EFFICIENCY_COLUMN_NAME = f"{REAR_SIDE_SYSTEM_NAME} {EFFICIENCY_NAME} %"
REAR_SIDE_SYSTEM_EFFICIENCY_DESCRIPTION = f"{SYMBOL_EFFICIENCY} {REAR_SIDE_SYSTEM_NAME} {EFFICIENCY_NAME}"
TOTAL_REAR_SIDE_SYSTEM_EFFICIENCY_EFFECT_COLUMN_NAME = (
    f"{TOTAL_NAME} {REAR_SIDE_SYSTEM_EFFICIENCY_COLUMN_NAME}"
)
UNIT_FOR_TOTAL_REAR_SIDE_SYSTEM_EFFICIENCY_EFFECT_COLUMN_NAME = (
    f"{UNIT_COLUMN_NAME_PREFIX} {TOTAL_REAR_SIDE_SYSTEM_EFFICIENCY_EFFECT_COLUMN_NAME}"
)
MEAN_REAR_SIDE_SYSTEM_EFFICIENCY_EFFECT_COLUMN_NAME = f"Mean {REAR_SIDE_SYSTEM_EFFICIENCY_COLUMN_NAME}"
UNIT_FOR_MEAN_REAR_SIDE_SYSTEM_EFFICIENCY_EFFECT_COLUMN_NAME = (
    f"{UNIT_COLUMN_NAME_PREFIX} {MEAN_REAR_SIDE_SYSTEM_EFFICIENCY_EFFECT_COLUMN_NAME}"
)
REAR_SIDE_SYSTEM_EFFICIENCY_EFFECT_PERCENTAGE_COLUMN_NAME = (
    f"{REAR_SIDE_SYSTEM_EFFICIENCY_COLUMN_NAME} {SYMBOL_PERCENTAGE}"
)

REAR_SIDE_SYSTEM_LOSS_DEFAULT = 1 - REAR_SIDE_SYSTEM_EFFICIENCY_DEFAULT
REAR_SIDE_SYSTEM_LOSS = f"{REAR_SIDE_SYSTEM_NAME} {LOSS_NAME}"
REAR_SIDE_SYSTEM_LOSS_COLUMN_NAME = f"{REAR_SIDE_SYSTEM_NAME} {LOSS_NAME} %"
REAR_SIDE_SYSTEM_LOSS_DESCRIPTION = f"{REAR_SIDE_SYSTEM_LOSS} & Degradation with age"

# Spectral effect

RESPONSIVITY = 'Responsivity'
RESPONSIVITY_COLUMN_NAME = RESPONSIVITY
RESPONSIVITY_SPECTRAL_DATA = 'responsivity'

REFERENCE_SPECTRUM = 'Reference Spectrum'
REFERENCE_SPECTRUM_COLUMN_NAME = REFERENCE_SPECTRUM
SPECTRUM_DATA = 'spectrum'

WAVELENGTHS_CSV_COLUMN_NAME_DEFAULT = 'Wavelength [nm]'
SPECTRAL_RESPONSIVITY_CSV_COLUMN_NAME_DEFAULT = 'Spectral Responsivity [A/W]'

SPECTRAL_FACTOR_MODEL_COLUMN_NAME = 'Spectral factor model'
SPECTRAL_FACTOR_DEFAULT = 1
SPECTRAL_FACTOR_NAME = "Spectral factor"
SPECTRAL_FACTOR_COLUMN_NAME = f"{SPECTRAL_FACTOR_NAME} *"
REAR_SIDE_SPECTRAL_FACTOR_COLUMN_NAME = f"{REAR_SIDE_NAME} {SPECTRAL_FACTOR_COLUMN_NAME}"

SPECTRAL_EFFECT_NAME = "Spectral effect"
SPECTRAL_EFFECT_COLUMN_NAME = f"{SPECTRAL_EFFECT_NAME} {SYMBOL_PLUS_MINUS}"
REAR_SIDE_SPECTRAL_EFFECT_COLUMN_NAME = f"{REAR_SIDE_NAME} {SPECTRAL_EFFECT_COLUMN_NAME}"
SPECTRAL_EFFECT_DESCRIPTION = (
    "Variation of spectrum between sunlight and artificial light"
)
TOTAL_SPECTRAL_EFFECT_COLUMN_NAME = f"{TOTAL_NAME} {SPECTRAL_EFFECT_COLUMN_NAME}"
UNIT_FOR_TOTAL_SPECTRAL_EFFECT_COLUMN_NAME = (
    f"{UNIT_COLUMN_NAME_PREFIX} {TOTAL_SPECTRAL_EFFECT_COLUMN_NAME}"
)
MEAN_SPECTRAL_EFFECT_COLUMN_NAME = f"Mean {SPECTRAL_EFFECT_COLUMN_NAME}"
UNIT_FOR_MEAN_SPECTRAL_EFFECT_COLUMN_NAME = (
    f"{UNIT_COLUMN_NAME_PREFIX} {MEAN_SPECTRAL_EFFECT_COLUMN_NAME}"
)
STANDARD_DEVIATION_SPECTRAL_EFFECT_COLUMN_NAME = (
    f"{STANDARD_DEVIATION_NAME} {SPECTRAL_EFFECT_COLUMN_NAME}"
)
SPECTRAL_EFFECT_PERCENTAGE = f"{SPECTRAL_EFFECT_NAME} {PERCENTAGE_NAME}"
REAR_SIDE_SPECTRAL_EFFECT_PERCENTAGE = f"{REAR_SIDE_NAME} {SPECTRAL_EFFECT_PERCENTAGE}"
SPECTRAL_EFFECT_PERCENTAGE_COLUMN_NAME = (
    f"{SPECTRAL_EFFECT_COLUMN_NAME} {SYMBOL_PERCENTAGE}"
)
REAR_SIDE_SPECTRAL_EFFECT_PERCENTAGE_COLUMN_NAME = f"{REAR_SIDE_NAME} {SPECTRAL_EFFECT_PERCENTAGE_COLUMN_NAME}"


REFLECTIVITY = f"{REFLECTIVITY_NAME}"
REFLECTIVITY_FACTOR_COLUMN_NAME = f"{REFLECTIVITY_NAME}"
REFLECTIVITY_EFFECT_NAME = f"{REFLECTIVITY_NAME} {EFFECT_NAME}"
REFLECTIVITY_EFFECT_COLUMN_NAME = f"{REFLECTIVITY_EFFECT_NAME} {SYMBOL_REFLECTIVITY}"
BEFORE_REFLECTIVITY = f"Before {REFLECTIVITY_NAME}"
AFTER_REFLECTIVITY = f"After {REFLECTIVITY_NAME}"
REFLECTIVITY_COLUMN_NAME = (
    f"{REFLECTIVITY_NAME} {SYMBOL_LOSS}"  # Losses due to angle of incidence
)
REAR_SIDE_REFLECTIVITY_COLUMN_NAME = f"{REAR_SIDE_NAME} {REFLECTIVITY_COLUMN_NAME}"
REFLECTIVITY_DESCRIPTION = (
    f"{REFLECTIVITY_NAME} as a function of the solar incidence angle"
)
REFLECTIVITY_EFFECT_DESCRIPTION = (
    f"{REFLECTIVITY_EFFECT_NAME} as a function of the solar incidence angle"
)
TOTAL_REFLECTIVITY_EFFECT_COLUMN_NAME = (
    f"{TOTAL_NAME} {REFLECTIVITY_EFFECT_COLUMN_NAME}"
)
UNIT_FOR_TOTAL_REFLECTIVITY_EFFECT_COLUMN_NAME = (
    f"{UNIT_COLUMN_NAME_PREFIX} {TOTAL_REFLECTIVITY_EFFECT_COLUMN_NAME}"
)
REFLECTIVITY_AVERAGE = f"Average {REFLECTIVITY}"  # Losses due to angle of incidence
REFLECTIVITY_AVERAGE_COLUMN_NAME = (
    f"{REFLECTIVITY_NAME} Average"  # Losses due to angle of incidence
)
MEAN_REFLECTIVITY_EFFECT_COLUMN_NAME = f"Mean {REFLECTIVITY_EFFECT_COLUMN_NAME}"
UNIT_FOR_MEAN_REFLECTIVITY_EFFECT_COLUMN_NAME = (
    f"{UNIT_COLUMN_NAME_PREFIX} {MEAN_REFLECTIVITY_EFFECT_COLUMN_NAME}"
)
STANDARD_DEVIATION_REFLECTIVITY_EFFECT_COLUMN_NAME = (
    f"{STANDARD_DEVIATION_NAME} {REFLECTIVITY_EFFECT_COLUMN_NAME}"
)
REFLECTIVITY_PERCENTAGE = (
    f"{REFLECTIVITY} {SYMBOL_PERCENTAGE}"  # Losses due to angle of incidence
)
REFLECTIVITY_PERCENTAGE_COLUMN_NAME = f"{REFLECTIVITY_COLUMN_NAME} {SYMBOL_PERCENTAGE}"  # Losses due to angle of incidence
REFLECTIVITY_EFFECT_PERCENTAGE_COLUMN_NAME = (
    f"{REFLECTIVITY_EFFECT_COLUMN_NAME} {SYMBOL_PERCENTAGE}"
)

REFLECTIVITY_EFFECT_COEFFICIENT = 0.155  # from PVGIS v5.2
ANGULAR_LOSS_COEFFICIENT = REFLECTIVITY_EFFECT_COEFFICIENT  # To Remove !
REFLECTIVITY_EFFECT_FLAG_DEFAULT = True
ANGULAR_LOSS_FACTOR_FLAG_DEFAULT = REFLECTIVITY_EFFECT_FLAG_DEFAULT  # To Remove !

TOTAL_NET_EFFECT_DESCRIPTION = f"{EFFECTS_NAME} due to {REFLECTIVITY_NAME}, {SPECTRAL_EFFECT_NAME}, {TEMPERATURE_AND_LOW_IRRADIANCE_NAME} and {SYSTEM_LOSS}"
# TOTAL_NET_EFFECT_DESCRIPTION = f"Effects due to reflectivity, spectral effect, temperature, low irradiance",
TOTAL_EFFECT_COLUMN_NAME = f"{TOTAL_EFFECT_NAME} {SYMBOL_PLUS_MINUS}"
UNIT_FOR_TOTAL_EFFECT_COLUMN_NAME = (
    f"{UNIT_COLUMN_NAME_PREFIX} {TOTAL_EFFECT_COLUMN_NAME}"
)
EFFECT_COLUMN_NAME = f"{EFFECT_NAME} {SYMBOL_PLUS_MINUS}"
MEAN_EFFECT_COLUMN_NAME = f"Mean {EFFECT_COLUMN_NAME}"
UNIT_FOR_MEAN_EFFECT_COLUMN_NAME = (
    f"{UNIT_COLUMN_NAME_PREFIX} {MEAN_EFFECT_COLUMN_NAME}"
)
EFFECT_PERCENTAGE_COLUMN_NAME = f"{EFFECT_COLUMN_NAME} {SYMBOL_PERCENTAGE}"

QUICK_RESPONSE_CODE_FLAG_DEFAULT = False
QUICK_RESPONSE_CODE_DESCRIPTION = f"{SYMBOL_QUICK_RESPONSE_TETRAGRAM} Quick-Response Code image (or a Base64 sequence) summarising inputs and performance"

STATISTICS_FLAG_DEFAULT = False
STATISTICS_DESCRIPTION = "Statistics"

GROUPBY_DESCRIPTION = "Group by"
GROUPBY_DEFAULT = None

NOMENCLATURE_FLAG_DEFAULT = False

CSV_FLAG_DEFAULT = False
CSV_PATH_DEFAULT = None
CSV_DESCRIPTION = "CSV output filename. Will override other output options !"

UNIPLOT_FLAG_DEFAULT = False
UNIPLOT_FLAG_DESCRIPTION = "Uniplot"

INDEX_IN_TABLE_OUTPUT_FLAG_DEFAULT = False
INDEX_IN_TABLE_OUTPUT_FLAG_DESCRIPTION = (
    "Index rows in output table (meaningful with at least `verbose >= 1`)"
)
INDEX_IN_TABLE_OUTPUT_FLAG_TYPER_HELP = (
    "Index rows in output table (meaningful with at least 1x -v)"
)

FINGERPRINT_FLAG_DEFAULT = False

LONGITUDE = "Longitude"
LATITUDE = "Latitude"

LONGITUDE_NAME = "Longitude"
LATITUDE_NAME = "Latitude"

TIME_ALGORITHM_NAME = "Timing"
TIMING_ALGORITHM_NAME = TIME_ALGORITHM_NAME

DECLINATION_NAME = "Declination"
HOUR_ANGLE_NAME = "Hour Angle"
POSITION_ALGORITHM_NAME = "Positioning"
POSITIONING_ALGORITHM_NAME = "Positioning"
ZENITH_NAME = "Zenith"
ALTITUDE_NAME = "Altitude"
AZIMUTH_NAME = "Azimuth"
ORIGIN_NAME = "Origin"
AZIMUTH_ORIGIN_NAME = f"{AZIMUTH_NAME} {ORIGIN_NAME}"
SURFACE_NAME = "Surface"

ORIENTATION_NAME = "Orientation"
SURFACE_ORIENTATION_NAME = f"{SURFACE_NAME} {ORIENTATION_NAME}"
TILT_NAME = "Tilt"
SURFACE_TILT_NAME = f"{SURFACE_NAME} {TILT_NAME}"

INCIDENCE_NAME = "Incidence"

SOLAR_NAME = "Solar"
EVENT_NAME = 'Event'
TIME_NAME = 'Time'

SOLAR_TIME_NAME = f"{SOLAR_NAME} {TIME_NAME}"
EVENT_TIME_NAME = f'{EVENT_NAME} {TIME_NAME}'

SOLAR_EVENT_NAME = f'{SOLAR_NAME} {EVENT_NAME}'
SOLAR_EVENTS_NAME = f'{SOLAR_NAME} {EVENT_NAME}s'
# SOLAR_EVENT_COLUMN_NAME = f'{SOLAR_EVENT_NAME} {SYMBOL_SUNRISE}'
SOLAR_EVENT_COLUMN_NAME = f'{EVENT_NAME} {SYMBOL_SUNRISE}'

SOLAR_EVENT_TIME_NAME = f'{SOLAR_EVENT_NAME} {TIME_NAME}'
# SOLAR_EVENT_TIME_COLUMN_NAME = f'{SOLAR_EVENT_TIME_NAME} {SYMBOL_TIMING}'
SOLAR_EVENT_TIME_COLUMN_NAME = f'{EVENT_TIME_NAME} {SYMBOL_TIMING}'

TITLE_KEY_NAME = "Title"

LONGITUDE_COLUMN_NAME = LONGITUDE_NAME + f" {SYMBOL_LONGITUDE}"
# LONGITUDE_DESCRIPTION = f"{SYMBOL_LONGITUDE} Longitude in decimal degrees ranging in [{LONGITUDE_MINIMUM}, {LONGITUDE_MAXIMUM}]"
LONGITUDE_DESCRIPTION = (
    f"{SYMBOL_LONGITUDE} Longitude in decimal {DEGREES}{SYMBOL_DEGREES}"
)

LATITUDE_COLUMN_NAME = LATITUDE_NAME + f" {SYMBOL_LATITUDE}"
# LATITUDE_DESCRIPTION = f"{SYMBOL_LATITUDE} Latitude in decimal degrees ranging in [{LATITUDE_MINIMUM}, {LATITUDE_MAXIMUM}]"
LATITUDE_DESCRIPTION = (
    f"{SYMBOL_LATITUDE} Latitude in decimal {DEGREES}{SYMBOL_DEGREES}"
)

ELEVATION_COLUMN_NAME = f"{ELEVATION_NAME} {SYMBOL_ELEVATION}"
ELEVATION_DESCRIPTION = (
    f"{SYMBOL_ELEVATION} Topographical {ELEVATION_NAME} in {SYMBOL_UNIT_ELEVATION_LONG}"
)

TIME_ALGORITHM_COLUMN_NAME = TIME_ALGORITHM_NAME + f" {SYMBOL_TIMING}"
TIMING_ALGORITHM_COLUMN_NAME = TIME_ALGORITHM_NAME + f" {SYMBOL_TIMING}"
TIME_ALGORITHM_DESCRIPTION = "Algorithm for solar time calculation"
TIMING_ALGORITHM_DESCRIPTION = "Algorithm for solar time calculation"

DECLINATION_COLUMN_NAME = DECLINATION_NAME + f" {SYMBOL_DECLINATION}"
HOUR_ANGLE_COLUMN_NAME = HOUR_ANGLE_NAME + f" {SYMBOL_HOUR_ANGLE}"
POSITION_ALGORITHM_COLUMN_NAME = POSITION_ALGORITHM_NAME + f" {SYMBOL_POSITIONING}"
POSITIONING_ALGORITHM_COLUMN_NAME = (
    POSITIONING_ALGORITHM_NAME + f" {SYMBOL_POSITIONING}"
)
POSITION_ALGORITHM_DESCRIPTION = "Algorithm for solar positioning"
POSITION_ALGORITHM_LIST_DESCRIPTION = "Solar position model(s). Select multiple using **Ctrl** and 🖱️ **left click**."
ZENITH_COLUMN_NAME = ZENITH_NAME + f" {SYMBOL_ZENITH}"
ALTITUDE_COLUMN_NAME = ALTITUDE_NAME + f" {SYMBOL_ALTITUDE}"
AZIMUTH_COLUMN_NAME = AZIMUTH_NAME + f" {SYMBOL_AZIMUTH}"
AZIMUTH_ORIGIN_COLUMN_NAME = AZIMUTH_ORIGIN_NAME + f" {SYMBOL_AZIMUTH}"
AZIMUTH_DIFFERENCE_COLUMN_NAME = AZIMUTH_NAME + f" {SYMBOL_AZIMUTH_DIFFERENCE}"

HORIZON_NAME = 'Horizon'
HORIZON_HEIGHT_NAME = HORIZON_NAME  + ' height'
HORIZON_HEIGHT_COLUMN_NAME = HORIZON_NAME + f" {SYMBOL_HORIZON}"
# HORIZON_HEIGHT_COLUMN_NAME = HORIZON_HEIGHT_NAME + f" {SYMBOL_HORIZON}"
HORIZON_PROFILE_DESCRIPTION = "Digital horizon model or a series of heights that form a horizon profile. If the keyword `'PVGIS'` is provided then the default horizon PVGIS data will automatically be selected. Otherwise, provide a list of heights (e.g., `10, 20, 30, 80`) for directions starting from north. The software will infer azimuth angles automatically in a clockwise order. If None, 0 height in any direction is considered."

ABOVE_HORIZON_COLUMN_NAME = "Above horizon"
LOW_ANGLE_COLUMN_NAME = "Low angle"
BELOW_HORIZON_COLUMN_NAME = "Below horizon"
BEHIND_HORIZON_NAME = 'Behind horizon'
BEHIND_HORIZON_COLUMN_NAME = BEHIND_HORIZON_NAME + f" {SYMBOL_HORIZON}"
POSITION_TO_HORIZON = "of horizon"
SOLAR_POSITIONS_TO_HORIZON_NAME = POSITION_TO_HORIZON
SOLAR_POSITIONS_TO_HORIZON_COLUMN_NAME = f"{SOLAR_POSITIONS_TO_HORIZON_NAME} {SYMBOL_HORIZON}"
SUN_HORIZON_NAME = "Sun-Horizon"
SUN_HORIZON_POSITIONS_NAME = f"{SUN_HORIZON_NAME} Positions {SYMBOL_HORIZON}"
SUN_HORIZON_POSITION_NAME = SUN_HORIZON_NAME
SUN_HORIZON_POSITION_COLUMN_NAME = f"{SUN_HORIZON_POSITION_NAME} {SYMBOL_HORIZON}"

VISIBLE_NAME = 'Visible'
VISIBLE_COLUMN_NAME = VISIBLE_NAME + f" {SYMBOL_VISIBLE}"

SURFACE_IN_SHADE_NAME = "In-shade"
SURFACE_IN_SHADE_COLUMN_NAME = f"{SURFACE_IN_SHADE_NAME} {SYMBOL_SHADING}"
SHADING_NAME = 'Shading'
SHADING_STATES_NAME = f"{SHADING_NAME} states"  # Set of states !
SHADING_STATES_COLUMN_NAME = f"{SHADING_STATES_NAME} {SYMBOL_SHADING}"
SHADING_STATE_NAME = f"{SHADING_NAME} state" # Which state for a moment
SHADING_STATE_COLUMN_NAME = f"{SHADING_STATE_NAME} {SYMBOL_SHADING}"
SHADING_ALGORITHM_NAME = 'Shading'
SHADING_ALGORITHM_COLUMN_NAME = SHADING_ALGORITHM_NAME + f" {SYMBOL_SHADING}"
SHADING_MODEL_DESCRIPTION = "Model to calculate shading for the location in question"

INCIDENCE_COLUMN_NAME = INCIDENCE_NAME + f" {SYMBOL_INCIDENCE}"
INCIDENCE_ALGORITHM_NAME = INCIDENCE_NAME + " algorithm"
INCIDENCE_ALGORITHM_COLUMN_NAME = INCIDENCE_ALGORITHM_NAME
INCIDENCE_ALGORITHM_DESCRIPTION = "Algorithm for solar incidence calculation"
INCIDENCE_DEFINITION = INCIDENCE_NAME + " angle"
COMPLEMENTARY_INCIDENCE_ANGLE_DEFINITION = f'Complementary {INCIDENCE_DEFINITION}'

SOLAR_TIME_COLUMN_NAME = "" + SOLAR_TIME_NAME
TIME_NAME = 'Time'
TIME_COLUMN_NAME = f'{TIME_NAME}'
LOCAL_TIME_COLUMN_NAME = f'Local {TIME_NAME}'

SURFACE_ORIENTATION_COLUMN_NAME = SURFACE_ORIENTATION_NAME + f" {SYMBOL_ORIENTATION}"
REAR_SIDE_SURFACE_ORIENTATION_COLUMN_NAME = f"{REAR_SIDE_NAME} {SURFACE_ORIENTATION_COLUMN_NAME}"
ANGLE_NAME = "Angle"
SURFACE_ORIENTATION_DESCRIPTION = (
    f"{SYMBOL_ORIENTATION} {SURFACE_ORIENTATION_NAME} {ANGLE_NAME}"
)
SURFACE_TILT_COLUMN_NAME = SURFACE_TILT_NAME + f" {SYMBOL_TILT}"
REAR_SIDE_SURFACE_TILT_COLUMN_NAME = f"{REAR_SIDE_NAME} {SURFACE_TILT_COLUMN_NAME}"
SURFACE_TILT_DESCRIPTION = f"{SYMBOL_TILT} {SURFACE_TILT_NAME} {ANGLE_NAME}"


NOT_AVAILABLE_COLUMN_NAME = "NA"
NOT_AVAILABLE = "NA"

OUT_OF_RANGE_INDICES_NAME = "Outbound"  # Out-of-range
OUT_OF_RANGE_INDICES_COLUMN_NAME = f"{OUT_OF_RANGE_INDICES_NAME} {SYMBOL_SYMMETRIC_DIFFERENCE}"

IRRADIANCE_UNIT = "W/m²"
IRRADIANCE_UNIT_K = "㎾/m²"
IRRADIANCE_COLUMN_NAME = f"{IRRADIANCE_NAME} {SYMBOL_IRRADIANCE}"
RELATIVE_IRRADIANCE_COLUMN_NAME = f"{IRRADIANCE_NAME} {SYMBOL_IRRADIANCE} %"
LOG_RELATIVE_IRRADIANCE_COLUMN_NAME = f"ln({IRRADIANCE_NAME} {SYMBOL_IRRADIANCE} %)"
LOW_IRRADIANCE_COLUMN_NAME = f"Low {IRRADIANCE_NAME}"

ALGORITHM_NAME = "Algorithm"
ALGORITHM_COLUMN_NAME = ALGORITHM_NAME
TEMPERATURE_ALGORITHM_COLUMN_NAME = ALGORITHM_NAME + f" {SYMBOL_TEMPERATURE}"

IRRADIANCE_SOURCE_COLUMN_NAME = (
    f"{IRRADIANCE_NAME} data source"  # Model or external data ?
)
RADIATION_MODEL_NAME = "Radiation model"
RADIATION_MODEL_COLUMN_NAME = RADIATION_MODEL_NAME + f" {SYMBOL_IRRADIANCE}"
HOFIERKA_2002 = "Hofierka 2002"
CLEAR_SKY_INDEX_MODELLING_NAME = f'{CLEAR_SKY_NAME} Index Modelling'

# acronyms in PVGIS' C source code commented
POWER_AT_STANDARD_TEST_CONDITIONS = 94.804  # P_STC
VOLTAGE_AT_STANDARD_TEST_CONDITIONS = 34.6  # V_STC
VOLTAGE_AT_STANDARD_TEST_CONDITIONS_COEFFICIENT_1 = 1.15  # C1
VOLTAGE_AT_STANDARD_TEST_CONDITIONS_COEFFICIENT_2 = -0.32  # C2
CURRENT_AT_STANDARD_TEST_CONDITIONS = 2.74  # I_STC
CURRENT_AT_STANDARD_TEST_CONDITIONS_TEMPERATURE_COEFFICIENT = 0.0033  # ALPHA_VM
VOLTAGE_AT_STANDARD_TEST_CONDITIONS_TEMPERATURE_COEFFICIENT = -0.159  # BETA_VM

# Energy

ENERGY_UNIT = "Wh"
ENERGY_UNIT_K = "㎾h"
PHOTOVOLTAIC_ENERGY_UNIT = ENERGY_UNIT

# Power


POWER_UNIT = "W"
POWER_UNIT_K = "㎾"
PHOTOVOLTAIC_POWER_UNIT = POWER_UNIT
POWER_NAME = "Power"
POWER_NAME_WITH_SYMBOL = f"{POWER_NAME} {SYMBOL_POWER}"
POWER_SHORTNAME = "P"

PEAK_POWER_UNIT = f"{POWER_UNIT_K}p"
PEAK_POWER_UNIT_NAME = 'Peak Power Unit'
PEAK_POWER_DEFAULT = 1  # kilowatt-peak
PEAK_POWER_MINIMUM = 0
PEAK_POWER_COLUMN_NAME = f"Peak {POWER_NAME}"
REAR_SIDE_PEAK_POWER_COLUMN_NAME = f"Peak {POWER_NAME}"
PEAK_POWER_DESCRIPTION = f"{SYMBOL_POWER} Peak power in {PEAK_POWER_UNIT}"
REAR_SIDE_PEAK_POWER_DESCRIPTION = f"{REAR_SIDE_NAME} {PEAK_POWER_DESCRIPTION}"

PHOTOVOLTAIC_POWER_SHORTNAME = f"{PHOTOVOLTAIC_SHORTNAME} {POWER_NAME}"
MEAN_PHOTOVOLTAIC_POWER_SHORTNAME = f"Mean {PHOTOVOLTAIC_SHORTNAME} {POWER_NAME}"
REAR_SIDE_PHOTOVOLTAIC_POWER_SHORTNAME = f"{REAR_SIDE_NAME} {PHOTOVOLTAIC_POWER_SHORTNAME}"

PHOTOVOLTAIC_POWER_NAME = f"{PHOTOVOLTAIC_SHORTNAME} {POWER_NAME}"
MEAN_PHOTOVOLTAIC_POWER_NAME = f"Mean {PHOTOVOLTAIC_SHORTNAME} {POWER_NAME}"

REAR_SIDE_PHOTOVOLTAIC_POWER_NAME = f"{REAR_SIDE_NAME} {PHOTOVOLTAIC_POWER_NAME}"

PHOTOVOLTAIC_POWER_LONG_NAME = f"{PHOTOVOLTAIC_NAME} {POWER_NAME}"
REAR_SIDE_PHOTOVOLTAIC_POWER_LONG_NAME = f"{REAR_SIDE_NAME} {PHOTOVOLTAIC_POWER_LONG_NAME}"

PHOTOVOLTAIC_POWER_COLUMN_NAME = f"{POWER_NAME} {SYMBOL_POWER}"
REAR_SIDE_PHOTOVOLTAIC_POWER_COLUMN_NAME = f"{REAR_SIDE_NAME} {PHOTOVOLTAIC_POWER_COLUMN_NAME}"

TOTAL_PHOTOVOLTAIC_POWER_COLUMN_NAME = (
    f"{TOTAL_EFFECT_COLUMN_NAME} {PHOTOVOLTAIC_POWER_COLUMN_NAME}"
)
REAR_SIDE_TOTAL_PHOTOVOLTAIC_POWER_COLUMN_NAME = f"{REAR_SIDE_NAME} {TOTAL_PHOTOVOLTAIC_POWER_COLUMN_NAME}"

UNIT_FOR_TOTAL_PHOTOVOLTAIC_POWER_COLUMN_NAME = (
    f"{UNIT_COLUMN_NAME_PREFIX} {TOTAL_PHOTOVOLTAIC_POWER_COLUMN_NAME}"
)

MEAN_PHOTOVOLTAIC_POWER_COLUMN_NAME = f"Mean {PHOTOVOLTAIC_POWER_COLUMN_NAME}"
MEAN_PHOTOVOLTAIC_POWER_COLUMN_NAME = f"{REAR_SIDE_NAME} {MEAN_PHOTOVOLTAIC_POWER_COLUMN_NAME}"

UNIT_FOR_MEAN_PHOTOVOLTAIC_POWER_COLUMN_NAME = (
    f"{UNIT_COLUMN_NAME_PREFIX} {MEAN_PHOTOVOLTAIC_POWER_COLUMN_NAME}"
)
STANDARD_DEVIATION_PHOTOVOLTAIC_POWER_COLUMN_NAME = (
    f"{STANDARD_DEVIATION_NAME} {PHOTOVOLTAIC_POWER_COLUMN_NAME}"
)

PHOTOVOLTAIC_ENERGY_COLUMN_NAME = f"{ENERGY_NAME} {SYMBOL_ENERGY}"
PHOTOVOLTAIC_ENERGY_NAME = f"{PHOTOVOLTAIC_NAME} {ENERGY_NAME}"
PHOTOVOLTAIC_ENERGY_LONG_NAME = f"{PHOTOVOLTAIC_NAME} {ENERGY_NAME}"
PHOTOVOLTAIC_ENERGY_LONG_COLUMN_NAME = f"{PHOTOVOLTAIC_ENERGY_NAME} {SYMBOL_ENERGY}"
UNIT_FOR_PHOTOVOLTAIC_ENERGY_COLUMN_NAME = (
    f"{UNIT_COLUMN_NAME_PREFIX} {PHOTOVOLTAIC_ENERGY_COLUMN_NAME}"
)
MEAN_PHOTOVOLTAIC_ENERGY_COLUMN_NAME = f"Mean {PHOTOVOLTAIC_ENERGY_COLUMN_NAME}"
UNIT_FOR_MEAN_PHOTOVOLTAIC_ENERGY_COLUMN_NAME = (
    f"{UNIT_COLUMN_NAME_PREFIX} {MEAN_PHOTOVOLTAIC_ENERGY_COLUMN_NAME}"
)

POWER_MODEL_NAME = f"{POWER_NAME} model"
POWER_MODEL_COLUMN_NAME = f"{POWER_MODEL_NAME} {SYMBOL_POWER}"
POWER_MODEL_DESCRIPTION = f"{SYMBOL_LETTER_F} {PHOTOVOLTAIC_POWER_LONG_NAME} model"
POWER_MODEL_LONG_DESCRIPTION = "Power-rating model of the effect of temperature, low irradiance and optionally wind speed on the power output."

PHOTOVOLTAIC_POWER_WITHOUT_SYSTEM_LOSS = (
    f"{PHOTOVOLTAIC_POWER_SHORTNAME} without {SYSTEM_LOSS}"
)

REAR_SIDE_PHOTOVOLTAIC_POWER_WITHOUT_SYSTEM_LOSS = (
    f"{REAR_SIDE_NAME} {PHOTOVOLTAIC_POWER_WITHOUT_SYSTEM_LOSS}"
)

PHOTOVOLTAIC_POWER_WITHOUT_SYSTEM_LOSS_COLUMN_NAME = (
    f"{POWER_NAME_WITH_SYMBOL} without {LOSS_NAME}"
)
REAR_SIDE_PHOTOVOLTAIC_POWER_WITHOUT_SYSTEM_LOSS_COLUMN_NAME = (
    f"{REAR_SIDE_NAME} {PHOTOVOLTAIC_POWER_WITHOUT_SYSTEM_LOSS_COLUMN_NAME}"
)

PHOTOVOLTAIC_POWER_WITHOUT_SYSTEM_LOSS_DESCRIPTION = (
    f"{PHOTOVOLTAIC_POWER_LONG_NAME} without {SYSTEM_LOSS}"
)
TOTAL_PHOTOVOLTAIC_POWER_WITHOUT_SYSTEM_LOSS_COLUMN_NAME = (
    f"{TOTAL_NAME} {PHOTOVOLTAIC_POWER_WITHOUT_SYSTEM_LOSS_COLUMN_NAME}"
)
UNIT_FOR_TOTAL_PHOTOVOLTAIC_POWER_WITHOUT_SYSTEM_LOSS_COLUMN_NAME = f"{UNIT_COLUMN_NAME_PREFIX} {TOTAL_PHOTOVOLTAIC_POWER_WITHOUT_SYSTEM_LOSS_COLUMN_NAME}"
MEAN_PHOTOVOLTAIC_POWER_WITHOUT_SYSTEM_LOSS_COLUMN_NAME = (
    f"Mean {PHOTOVOLTAIC_POWER_WITHOUT_SYSTEM_LOSS_COLUMN_NAME}"
)
UNIT_FOR_MEAN_PHOTOVOLTAIC_POWER_WITHOUT_SYSTEM_LOSS_COLUMN_NAME = f"{UNIT_COLUMN_NAME_PREFIX} {MEAN_PHOTOVOLTAIC_POWER_WITHOUT_SYSTEM_LOSS_COLUMN_NAME}"
STANDARD_DEVIATION_PHOTOVOLTAIC_POWER_WITHOUT_SYSTEM_LOSS_COLUMN_NAME = (
    f"{STANDARD_DEVIATION_NAME} {PHOTOVOLTAIC_POWER_WITHOUT_SYSTEM_LOSS_COLUMN_NAME}"
)

DIRECT_CURRENT = "⎓"
DIRECT_CURRENT_COLUMN_NAME = "STC ⎓"
VOLTAGE_COLUMN_NAME = "STC ⚡"

RADIATION_CUTOFF_THRESHHOLD = 0
RADIATION_CUTOFF = 30.0  # from PVGIS v5.2
RADIATION_CUTOFF_THRESHOLD_DESCRIPTION = "Radiation cutoff threshold"

# Irradiance

IRRADIANCE_COMPONENT_TYPER_HELP_ADDENDUM = "over a time series"

GLOBAL_IRRADIANCE_TYPER_HELP_SHORT = (
    f"{SYMBOL_IRRADIANCE} Calculate the global irradiance"
)
GLOBAL_IRRADIANCE_TYPER_HELP = (
    f"{GLOBAL_IRRADIANCE_TYPER_HELP_SHORT} {IRRADIANCE_COMPONENT_TYPER_HELP_ADDENDUM}"
)

DIRECT_IRRADIANCE_TYPER_HELP_SHORT = f"{SYMBOL_DIRECT} Calculate the direct irradiance"
DIRECT_IRRADIANCE_TYPER_HELP = (
    f"{DIRECT_IRRADIANCE_TYPER_HELP_SHORT} {IRRADIANCE_COMPONENT_TYPER_HELP_ADDENDUM}"
)

DIFFUSE_IRRADIANCE_TYPER_HELP_SHORT = (
    f"{SYMBOL_DIFFUSE} Calculate the diffuse irradiance"
)
DIFFUSE_IRRADIANCE_TYPER_HELP = (
    f"{DIFFUSE_IRRADIANCE_TYPER_HELP_SHORT} {IRRADIANCE_COMPONENT_TYPER_HELP_ADDENDUM}"
)

REFLECTED_IRRADIANCE_TYPER_HELP_SHORT = (
    f"{SYMBOL_REFLECTED} Calculate the clear-sky ground reflected irradiance"
)
REFLECTED_IRRADIANCE_TYPER_HELP = f"{REFLECTED_IRRADIANCE_TYPER_HELP_SHORT} {IRRADIANCE_COMPONENT_TYPER_HELP_ADDENDUM}"

EXTRATERRESTRIAL_IRRADIANCE_TYPER_HELP_SHORT = (
    f"{SYMBOL_CLEAR_SKY} Calculate the extraterrestrial normal irradiance"
)
EXTRATERRESTRIAL_IRRADIANCE_TYPER_HELP = f"{EXTRATERRESTRIAL_IRRADIANCE_TYPER_HELP_SHORT} {IRRADIANCE_COMPONENT_TYPER_HELP_ADDENDUM}"

EFFECTIVE_POWER_NAME = f"{EFFECTIVE_NAME} {POWER_NAME}"
EFFECTIVE_POWER_COLUMN_NAME = f"{EFFECTIVE_POWER_NAME} {SYMBOL_EFFECTIVE}"
EFFECTIVE_IRRADIANCE_NAME = f"{EFFECTIVE_NAME} {IRRADIANCE_NAME}"
EFFECTIVE_IRRADIANCE_COLUMN_NAME = f"{EFFECTIVE_IRRADIANCE_NAME} {SYMBOL_EFFECTIVE}"
IRRADIANCE_AFTER_REFLECTIVITY = f"{IRRADIANCE_NAME} {AFTER_REFLECTIVITY}"
IRRADIANCE_AFTER_REFLECTIVITY_DESCRIPTION = (
    f"{GLOBAL_NAME} {IN_PLANE_NAME} {IRRADIANCE_NAME} {AFTER_REFLECTIVITY}"
)
IN_PLANE_IRRADIANCE_COLUMN_NAME = f"{IN_PLANE_IRRADIANCE_NAME} {SYMBOL_INCLINED}"
INCLINED_IRRADIANCE_COLUMN_NAME = f"{INCLINED_IRRADIANCE_NAME} {SYMBOL_INCLINED}"

GLOBAL_IRRADIANCE_NAME = f"{GLOBAL_NAME} {IRRADIANCE_NAME}"
GLOBAL_EFFECTIVE_IRRADIANCE = f"{EFFECTIVE_NAME} {GLOBAL_IRRADIANCE_NAME}"
GLOBAL_EFFECTIVE_IRRADIANCE_COLUMN_NAME = (
    f"{EFFECTIVE_NAME} {GLOBAL_IRRADIANCE_NAME} {SYMBOL_EFFECTIVE}"
)

# In-plane
GLOBAL_IN_PLANE_IRRADIANCE = f"{GLOBAL_NAME} {IN_PLANE_NAME} {IRRADIANCE_NAME}"
GLOBAL_IN_PLANE_IRRADIANCE_COLUMN_NAME = f"{GLOBAL_IRRADIANCE_NAME} {SYMBOL_IN_PLANE}"

TOTAL_GLOBAL_IN_PLANE_IRRADIANCE_COLUMN_NAME = (
    f"{TOTAL_NAME} {GLOBAL_IRRADIANCE_NAME} {SYMBOL_IN_PLANE}"
)
MEAN_GLOBAL_IN_PLANE_IRRADIANCE_COLUMN_NAME = (
    f"Meam {GLOBAL_IN_PLANE_IRRADIANCE_COLUMN_NAME}"
)
STANDARD_DEVIATION_GLOBAL_IN_PLANE_IRRADIANCE_COLUMN_NAME = (
    f"{STANDARD_DEVIATION_NAME} {GLOBAL_IN_PLANE_IRRADIANCE_COLUMN_NAME}"
)

GLOBAL_IN_PLANE_IRRADIANCE_REFLECTIVITY = (
    f"{GLOBAL_IN_PLANE_IRRADIANCE} {REFLECTIVITY_NAME}"
)
GLOBAL_IN_PLANE_IRRADIANCE_REFLECTIVITY_COLUMN_NAME = (
    f"{IN_PLANE_IRRADIANCE_NAME} {REFLECTIVITY_COLUMN_NAME}"
)

GLOBAL_IN_PLANE_IRRADIANCE_BEFORE_REFLECTIVITY = (
    f"{IN_PLANE_IRRADIANCE_NAME} {BEFORE_REFLECTIVITY}"
)
GLOBAL_IN_PLANE_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME = (
    f"{IN_PLANE_IRRADIANCE_NAME} {SYMBOL_SUN}"
)
GLOBAL_IN_PLANE_IRRADIANCE_BEFORE_REFLECTIVITY_DESCRIPTION = f"{GLOBAL_NAME} {IN_PLANE_NAME} (or {INCLINED_NAME}) {IRRADIANCE_NAME} {BEFORE_REFLECTIVITY}"
TOTAL_GLOBAL_IN_PLANE_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME = (
    f"{TOTAL_NAME} {GLOBAL_IN_PLANE_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME}"
)
UNIT_FOR_TOTAL_GLOBAL_IN_PLANE_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME = f"{UNIT_COLUMN_NAME_PREFIX} {TOTAL_GLOBAL_IN_PLANE_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME}"

GLOBAL_IN_PLANE_IRRADIANCE_AFTER_REFLECTIVITY = (
    f"{GLOBAL_IRRADIANCE_NAME} {AFTER_REFLECTIVITY}"
)
GLOBAL_IN_PLANE_IRRADIANCE_AFTER_REFLECTIVITY_COLUMN_NAME = (
    f"{GLOBAL_IN_PLANE_IRRADIANCE}"
)
GLOBAL_IN_PLANE_IRRADIANCE_AFTER_REFLECTIVITY_DESCRIPTION = (
    f"{GLOBAL_IRRADIANCE_NAME} {AFTER_REFLECTIVITY}"
)
UNIT_FOR_GLOBAL_IN_PLANE_IRRADIANCE_AFTER_REFLECTIVITY_COLUMN_NAME = f"{UNIT_COLUMN_NAME_PREFIX} {GLOBAL_IN_PLANE_IRRADIANCE_AFTER_REFLECTIVITY_COLUMN_NAME}"
MEAN_GLOBAL_IN_PLANE_IRRADIANCE_AFTER_REFLECTIVITY_COLUMN_NAME = (
    f"Mean {GLOBAL_IN_PLANE_IRRADIANCE_AFTER_REFLECTIVITY_COLUMN_NAME}"
)
UNIT_FOR_MEAN_GLOBAL_IN_PLANE_IRRADIANCE_AFTER_REFLECTIVITY_COLUMN_NAME = f"{UNIT_COLUMN_NAME_PREFIX} {MEAN_GLOBAL_IN_PLANE_IRRADIANCE_AFTER_REFLECTIVITY_COLUMN_NAME}"

MEAN_GLOBAL_IN_PLANE_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME = (
    f"Mean {GLOBAL_IN_PLANE_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME}"
)
UNIT_FOR_MEAN_GLOBAL_IN_PLANE_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME = f"{UNIT_COLUMN_NAME_PREFIX} {MEAN_GLOBAL_IN_PLANE_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME}"
STANDARD_DEVIATION_GLOBAL_IN_PLANE_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME = f"{STANDARD_DEVIATION_NAME} {GLOBAL_IN_PLANE_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME}"

# Homonyms to Inclined
GLOBAL_INCLINED_IRRADIANCE = f"{GLOBAL_NAME} {INCLINED_IRRADIANCE_NAME}"
GLOBAL_INCLINED_IRRADIANCE_COLUMN_NAME = f"{GLOBAL_NAME} {SYMBOL_INCLINED}"
REAR_SIDE_GLOBAL_INCLINED_IRRADIANCE_COLUMN_NAME = f"{REAR_SIDE_NAME} {GLOBAL_INCLINED_IRRADIANCE_COLUMN_NAME}"
GLOBAL_INCLINED_IRRADIANCE_REFLECTIVITY = (
    f"{GLOBAL_INCLINED_IRRADIANCE} {REFLECTIVITY_NAME}"
)
GLOBAL_INCLINED_IRRADIANCE_REFLECTIVITY_COLUMN_NAME = (
    f"{GLOBAL_NAME} {REFLECTIVITY_COLUMN_NAME}"
)
GLOBAL_INCLINED_IRRADIANCE_BEFORE_REFLECTIVITY = (
    f"{GLOBAL_IRRADIANCE_NAME} {BEFORE_REFLECTIVITY}"
)
GLOBAL_INCLINED_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME = (
    f"{GLOBAL_INCLINED_IRRADIANCE_COLUMN_NAME} {SYMBOL_SUN}"
)
REAR_SIDE_GLOBAL_INCLINED_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME = (
    f"{REAR_SIDE_NAME} {GLOBAL_INCLINED_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME}"
)
# GLOBAL_INCLINED_IRRADIANCE_BEFORE_REFLECTIVITY_DESCRIPTION = f'{GLOBAL_IRRADIANCE_NAME} {BEFORE_REFLECTIVITY}'
GLOBAL_INCLINED_IRRADIANCE_BEFORE_REFLECTIVITY_DESCRIPTION = f"{GLOBAL_NAME} {IN_PLANE_NAME} (or {INCLINED_NAME}) {IRRADIANCE_NAME} {BEFORE_REFLECTIVITY}"
GLOBAL_INCLINED_IRRADIANCE_AFTER_REFLECTIVITY = (
    f"{GLOBAL_IRRADIANCE_NAME} {AFTER_REFLECTIVITY}"
)
GLOBAL_INCLINED_IRRADIANCE_AFTER_REFLECTIVITY_COLUMN_NAME = (
    f"{GLOBAL_INCLINED_IRRADIANCE}"
)
GLOBAL_INCLINED_IRRADIANCE_AFTER_REFLECTIVITY_DESCRIPTION = (
    f"{GLOBAL_IRRADIANCE_NAME} {AFTER_REFLECTIVITY}"
)
GLOBAL_HORIZONTAL_IRRADIANCE = GLOBAL_IRRADIANCE_NAME
GLOBAL_HORIZONTAL_IRRADIANCE_COLUMN_NAME = (
    f"{GLOBAL_HORIZONTAL_IRRADIANCE} {SYMBOL_HORIZONTAL}"
)
GLOBAL_HORIZONTAL_IRRADIANCE_DESCRIPTION = (
    f"{GLOBAL_NAME} {HORIZONTAL_NAME} {IRRADIANCE_NAME}"
)
GLOBAL_HORIZONTAL_IRRADIANCE_SOURCE_COLUMN_NAME = f'{GLOBAL_HORIZONTAL_IRRADIANCE} data source'

EFFECTIVE_GLOBAL_IRRADIANCE_COLUMN_NAME = f"{GLOBAL_NAME} {SYMBOL_EFFECTIVE}"
REAR_SIDE_EFFECTIVE_GLOBAL_IRRADIANCE_COLUMN_NAME = f"{REAR_SIDE_NAME} {EFFECTIVE_GLOBAL_IRRADIANCE_COLUMN_NAME}"

EFFECTIVE_GLOBAL_IRRADIANCE_DESCRIPTION = (
    "Inclined irradiance after changes due to various factors"
)
EFFECTIVE_IRRADIANCE_COLUMN_NAME = EFFECTIVE_GLOBAL_IRRADIANCE_COLUMN_NAME
UNIT_FOR_EFFECTIVE_IRRADIANCE_COLUMN_NAME = (
    f"{UNIT_COLUMN_NAME_PREFIX} {EFFECTIVE_IRRADIANCE_COLUMN_NAME}"
)
MEAN_EFFECTIVE_IRRADIANCE_COLUMN_NAME = (
    f"Mean {EFFECTIVE_GLOBAL_IRRADIANCE_COLUMN_NAME}"
)
UNIT_FOR_MEAN_EFFECTIVE_IRRADIANCE_COLUMN_NAME = (
    f"{UNIT_COLUMN_NAME_PREFIX} {MEAN_EFFECTIVE_IRRADIANCE_COLUMN_NAME}"
)

DIRECT_NAME = "Direct"
DIRECT_IRRADIANCE_NAME = f"{DIRECT_NAME} {IRRADIANCE_NAME}"
EFFECTIVE_DIRECT_IRRADIANCE_COLUMN_NAME = f"{DIRECT_NAME} {SYMBOL_EFFECTIVE}"
REAR_SIDE_EFFECTIVE_DIRECT_IRRADIANCE_COLUMN_NAME = f"{REAR_SIDE_NAME} {EFFECTIVE_DIRECT_IRRADIANCE_COLUMN_NAME}"
DIRECT_INCLINED_IRRADIANCE = f"{DIRECT_IRRADIANCE_NAME}"
DIRECT_INCLINED_IRRADIANCE_COLUMN_NAME = f"{DIRECT_NAME} {SYMBOL_INCLINED}"
REAR_SIDE_DIRECT_INCLINED_IRRADIANCE_COLUMN_NAME = f"{REAR_SIDE_NAME} {DIRECT_INCLINED_IRRADIANCE_COLUMN_NAME}"

DIRECT_INCLINED_IRRADIANCE_REFLECTIVITY = f"{DIRECT_INCLINED_IRRADIANCE} {REFLECTIVITY}"
DIRECT_INCLINED_IRRADIANCE_REFLECTIVITY_COLUMN_NAME = (
    f"{DIRECT_NAME} {REFLECTIVITY_COLUMN_NAME}"
)
REAR_SIDE_DIRECT_INCLINED_IRRADIANCE_REFLECTIVITY_COLUMN_NAME = (
    f"{REAR_SIDE_NAME} {DIRECT_INCLINED_IRRADIANCE_REFLECTIVITY_COLUMN_NAME}"
)

DIRECT_INCLINED_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME = (
    f"{DIRECT_INCLINED_IRRADIANCE_COLUMN_NAME} {SYMBOL_SUN}"
)
REAR_SIDE_DIRECT_INCLINED_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME = (
    f"{REAR_SIDE_NAME} {DIRECT_INCLINED_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME}"
)

DIRECT_HORIZONTAL_IRRADIANCE = f"{DIRECT_IRRADIANCE_NAME}"
DIRECT_HORIZONTAL_IRRADIANCE_COLUMN_NAME = (
    f"{DIRECT_HORIZONTAL_IRRADIANCE} {SYMBOL_HORIZONTAL}"
)
REAR_SIDE_DIRECT_HORIZONTAL_IRRADIANCE_COLUMN_NAME = (
    f"{REAR_SIDE_NAME} {DIRECT_HORIZONTAL_IRRADIANCE_COLUMN_NAME}"
)
DIRECT_HORIZONTAL_IRRADIANCE_DESCRIPTION = (
    f"{DIRECT_NAME} {HORIZONTAL_NAME} {IRRADIANCE_NAME}"
)
DIRECT_HORIZONTAL_IRRADIANCE_SOURCE_COLUMN_NAME = f'{DIRECT_HORIZONTAL_IRRADIANCE} data source'

DIRECT_NORMAL_IRRADIANCE = f"{DIRECT_IRRADIANCE_NAME} {NORMAL_NAME}"
DIRECT_NORMAL_IRRADIANCE_COLUMN_NAME = f"{DIRECT_HORIZONTAL_IRRADIANCE} {SYMBOL_NORMAL}"

DIFFUSE_NAME = "Diffuse"
DIFFUSE_IRRADIANCE_NAME = f"{DIFFUSE_NAME} {IRRADIANCE_NAME}"
DIFFUSE_INCLINED_IRRADIANCE = f"{DIFFUSE_IRRADIANCE_NAME} inclined"
DIFFUSE_HORIZONTAL_IRRADIANCE = f"{DIFFUSE_IRRADIANCE_NAME} horizontal"
DIFFUSE_CLEAR_SKY_IRRADIANCE = f"{DIFFUSE_IRRADIANCE_NAME} clear-sky"
EFFECTIVE_DIFFUSE_IRRADIANCE_COLUMN_NAME = f"{DIFFUSE_NAME} {SYMBOL_EFFECTIVE}"
REAR_SIDE_EFFECTIVE_DIFFUSE_IRRADIANCE_COLUMN_NAME = f"{REAR_SIDE_NAME} {EFFECTIVE_DIFFUSE_IRRADIANCE_COLUMN_NAME}"
DIRECT_INCLINED_IRRADIANCE = f"{DIRECT_IRRADIANCE_NAME}"
DIFFUSE_INCLINED_IRRADIANCE_COLUMN_NAME = f"{DIFFUSE_NAME} {SYMBOL_INCLINED}"
REAR_SIDE_DIFFUSE_INCLINED_IRRADIANCE_COLUMN_NAME = f"{REAR_SIDE_NAME} {DIFFUSE_INCLINED_IRRADIANCE_COLUMN_NAME}"
DIFFUSE_INCLINED_IRRADIANCE_REFLECTIVITY_COLUMN_NAME = (
    f"{DIFFUSE_NAME} {REFLECTIVITY_COLUMN_NAME}"
)
REAR_SIDE_DIFFUSE_INCLINED_IRRADIANCE_REFLECTIVITY_COLUMN_NAME = (
    f"{REAR_SIDE_NAME} {DIFFUSE_INCLINED_IRRADIANCE_REFLECTIVITY_COLUMN_NAME}"
)
DIFFUSE_INCLINED_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME = (
    f"{DIFFUSE_NAME} {SYMBOL_INCLINED} {SYMBOL_SUN}"  # 🗤⟀
)
REAR_SIDE_DIFFUSE_INCLINED_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME = (
    f"{REAR_SIDE_NAME} {DIFFUSE_INCLINED_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME}"
)
DIFFUSE_HORIZONTAL_IRRADIANCE_COLUMN_NAME = f"{DIFFUSE_NAME} {SYMBOL_HORIZONTAL}"
REAR_SIDE_DIFFUSE_HORIZONTAL_IRRADIANCE_COLUMN_NAME = f"{REAR_SIDE_NAME} {DIFFUSE_HORIZONTAL_IRRADIANCE_COLUMN_NAME}"
DIFFUSE_CLEAR_SKY_IRRADIANCE_COLUMN_NAME = f"{DIFFUSE_NAME} {SYMBOL_CLEAR_SKY}"

REFLECTED_NAME = "Reflected"
REFLECTED_IRRADIANCE_NAME = f"{REFLECTED_NAME} {IRRADIANCE_NAME}"
REFLECTED_INCLINED_IRRADIANCE = f"{REFLECTED_IRRADIANCE_NAME}"
EFFECTIVE_REFLECTED_IRRADIANCE_COLUMN_NAME = f"{REFLECTED_NAME} {SYMBOL_EFFECTIVE}"
REAR_SIDE_EFFECTIVE_REFLECTED_IRRADIANCE_COLUMN_NAME = f"{REAR_SIDE_NAME} {EFFECTIVE_REFLECTED_IRRADIANCE_COLUMN_NAME}"
REFLECTED_INCLINED_IRRADIANCE_COLUMN_NAME = f"{REFLECTED_NAME} {SYMBOL_INCLINED}"
REAR_SIDE_REFLECTED_INCLINED_IRRADIANCE_COLUMN_NAME = f"{REAR_SIDE_NAME} {REFLECTED_INCLINED_IRRADIANCE_COLUMN_NAME}"
REFLECTED_INCLINED_IRRADIANCE_REFLECTIVITY_COLUMN_NAME = (
    f"{REFLECTED_NAME} {REFLECTIVITY_COLUMN_NAME}"
)
REAR_SIDE_REFLECTED_INCLINED_IRRADIANCE_REFLECTIVITY_COLUMN_NAME = (
    f"{REAR_SIDE_NAME} {REFLECTED_INCLINED_IRRADIANCE_REFLECTIVITY_COLUMN_NAME}"
)
REFLECTED_INCLINED_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME = (
    f"{REFLECTED_NAME} {SYMBOL_INCLINED} {SYMBOL_SUN}"
)
REAR_SIDE_REFLECTED_INCLINED_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME = (
    f"{REAR_SIDE_NAME} {REFLECTED_INCLINED_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME}"
)
REFLECTED_HORIZONTAL_IRRADIANCE_COLUMN_NAME = f"{REFLECTED_NAME} {SYMBOL_HORIZONTAL}"

VIEW_FRACTION = "View fraction"
VIEW_FRACTION_COLUMN_NAME = "View %"

EXTRATERRESTRIAL_NAME = "Extra"
EXTRATERRESTRIAL_NORMAL_IRRADIANCE = f"{EXTRATERRESTRIAL_NAME} {NORMAL_NAME}"
EXTRATERRESTRIAL_HORIZONTAL_IRRADIANCE = f"{EXTRATERRESTRIAL_NAME} {HORIZONTAL_NAME}"
EXTRATERRESTRIAL_NORMAL_IRRADIANCE_COLUMN_NAME = (
    f"{EXTRATERRESTRIAL_NAME} {SYMBOL_NORMAL}"
)
EXTRATERRESTRIAL_HORIZONTAL_IRRADIANCE_COLUMN_NAME = (
    f"{EXTRATERRESTRIAL_NAME} {SYMBOL_HORIZONTAL}"
)

COMPLEMENTARY_INCIDENCE_ANGLE_DEFAULT = False  # Sun-to-Surface-Normal
COMPLEMENTARY_INCIDENCE_ANGLE_TRUE = True  # Sun-to-Surface-Plane
ZERO_NEGATIVE_INCIDENCE_ANGLE_DEFAULT = True
ZERO_NEGATIVE_INCIDENCE_ANGLE_DESCRIPTION = (
    "Set negative solar incidence angle values to zero"
)
DO_NOT_ZERO_NEGATIVE_INCIDENCE_ANGLE_DEFAULT = False
DO_NOT_ZERO_NEGATIVE_INCIDENCE_ANGLE_DESCRIPTION = (
    f"Do not {ZERO_NEGATIVE_INCIDENCE_ANGLE_DESCRIPTION}"
)

ANNUAL_ENERGY_COLUMN_NAME = f"{ANNUAL_NAME} {ENERGY_NAME}"
MONTHLY_ENERGY_COLUMN_NAME = f"{MONTHLY_NAME} {ENERGY_NAME}"
DAILY_ENERGY_COLUMN_NAME = f"{DAILY_NAME} {ENERGY_NAME}"
DAILY_LOST_ENERGY_COLUMN_NAME = f"{DAILY_NAME} Lost {ENERGY_NAME}"
MISSED_ENERGY_COLUMN_NAME = f"{DAILY_NAME} Missed {ENERGY_NAME}"
MONTHLY_STANDARD_DEVIATION_COLUMN_NAME = f"{MONTHLY_NAME} {STANDARD_DEVIATION_NAME}"
ANNUAL_STANDARD_DEVIATION_COLUMN_NAME = f"{ANNUAL_NAME} {STANDARD_DEVIATION_NAME}"
# ANGLE_OF_INCIDENCE_COLUMN_NAME = f'{ANGLE_OF_INCIDENCE_NAME} {SYMBOL_INCIDENCE}'
TEMPERATURE_AND_LOW_IRRADIANCE_COLUMN_NAME = (
    f"{TEMPERATURE_AND_LOW_IRRADIANCE_NAME} {EFFECT_NAME}"
)
TEMPERATURE_AND_LOW_IRRADIANCE_EFFECT_COLUMN_NAME = (
    TEMPERATURE_AND_LOW_IRRADIANCE_COLUMN_NAME  # Keep only one !
)
# TEMPERATURE_AND_LOW_IRRADIANCE_DESCRIPTION = f'Difference between real conditions and standard conditions, should be close to zero ?'
TEMPERATURE_AND_LOW_IRRADIANCE_DESCRIPTION = (
    f"{TEMPERATURE_AND_LOW_IRRADIANCE_NAME} {EFFECT_NAME}"
)
TOTAL_TEMPERATURE_AND_LOW_IRRADIANCE_EFFECT_COLUMN_NAME = (
    f"{TOTAL_NAME} {TEMPERATURE_AND_LOW_IRRADIANCE_EFFECT_COLUMN_NAME}"
)
UNIT_FOR_TEMPERATURE_AND_LOW_IRRADIANCE_EFFECT_COLUMN_NAME = (
    f"{UNIT_COLUMN_NAME_PREFIX} {TEMPERATURE_AND_LOW_IRRADIANCE_EFFECT_COLUMN_NAME}"
)
MEAN_TEMPERATURE_AND_LOW_IRRADIANCE_EFFECT_COLUMN_NAME = (
    f"Mean {TEMPERATURE_AND_LOW_IRRADIANCE_EFFECT_COLUMN_NAME}"
)
UNIT_FOR_MEAN_TEMPERATURE_AND_LOW_IRRADIANCE_EFFECT_COLUMN_NAME = f"{UNIT_COLUMN_NAME_PREFIX} {MEAN_TEMPERATURE_AND_LOW_IRRADIANCE_EFFECT_COLUMN_NAME}"
TEMPERATURE_AND_LOW_IRRADIANCE_EFFECT_PERCENTAGE_COLUMN_NAME = (
    f"{TEMPERATURE_AND_LOW_IRRADIANCE_EFFECT_COLUMN_NAME} {SYMBOL_PERCENTAGE}"
)

TOTAL_LOSS_COLUMN_NAME = f"{TOTAL_NAME} {LOSS_NAME}"

# Analysis

ANALYSIS_FLAG_DEFAULT = False
ANALYSIS_FLAG_TRUE = True
ANALYSIS_DESCRIPTION = f"{SYMBOL_CALCULATOR} Analysis of performance. Will force detailed calculations internally (`verbose>=9` and `quiet=True`) and report along with basic Information for location, surface position, photovoltaic cell technology, peak power and mount type, the requested level of details, i.e. `Minimal` reports : {PHOTOVOLTAIC_ENERGY_COLUMN_NAME}, `Simple` reports in addition {TOTAL_GLOBAL_IN_PLANE_IRRADIANCE_BEFORE_REFLECTIVITY_COLUMN_NAME} and {TOTAL_EFFECT_COLUMN_NAME}, `Advanced` reports in addition in-between figures for the gain/loss due to various effects and `Extended` will report in addition almost all intermediate quantities."


# for Output options, features, etc.

FINGERPRINT_NAME = "Fingerprint"
FINGERPRINT_COLUMN_NAME = f"{FINGERPRINT_NAME} {SYMBOL_FINGERPRINT}"
FINGERPRINT_DESCRIPTION = f"{SYMBOL_FINGERPRINT} {FINGERPRINT_NAME} the {PHOTOVOLTAIC_POWER_LONG_NAME} output time series"


# from PVGIS

PERFORMANCE_RATIO = 0.68
DUST_TRANSMITTANCE = 1.00
TEMPERATURE_INTERVAL = 1
T_COEFF = 0.035
THRESHOLD = 0.0001
INVERTER_EFF = 0.97
START_VOLTAGE = 14.5
DEFAULT_CONSUMPTION_FILE = "hourlyconsumption.txt"
DEFAULT_COEFFICIENTS_FILE = "csi.coeffs"
DEFAULT_POWER_MATRIX_FILE = "matrix_voltages.csv"
DEFAULT_CHARGE_MATRIX_FILE = "battery_voltage.csv"

MAX_CURRENTS = 20
MAX_STATES = 20
chargeMatrix = [0.0] * (MAX_CURRENTS * MAX_STATES)

CACHE_MAXSIZE = 24
