"""
This file `constants.py` contains important hard-coded values for
`pvgisprototype`'s components.

The content is sectioned to ease-of reviewing and updating.
"""

from math import pi
import numpy as np


# Symbols to use ?
# ⊾ ∢ ⦠ ∡ ⦛ ⦜ ⦣ ⦤ ⦥
# ⦨ ⦩ # from horizontal upwards
# ⦪ ⦫ # from horizontal downwards
# ⦮ ⦯ # from vertical upwards
# ⦬ ⦭ # from vertical downwards
# ⭍ ⌁
# ☀ ☼ 🌣 # sun
# 🗤 # rays spreading
# ⌇ # wavy line
# 🌬 # wind
# ⌖ ⯐ # position
# ⭸ ⭹

FINGERPRINT_COLUMN_NAME = ' Fingerprint'
DATA_TYPE_DEFAULT = 'float32'  # takes halve of the time to process than float64
ARRAY_BACKEND_DEFAULT = 'NUMPY'  # OR 'CUPY', 'DASK'
VERBOSE_LEVEL_DEFAULT = 0
HASH_AFTER_THIS_VERBOSITY_LEVEL = 6
DEBUG_AFTER_THIS_VERBOSITY_LEVEL = 7
ROUNDING_PLACES_DEFAULT = 5
TOLERANCE_DEFAULT = 0.1  # Is this a sane default ?
UNITLESS = 'Unitless'
RADIANS = 'radians'
DEGREES = 'degrees'
ANGLE_OUTPUT_UNITS_DEFAULT = RADIANS
MINUTES = 'minutes'
TIME_OUTPUT_UNITS_DEFAULT = MINUTES
IN_MEMORY_FLAG_DEFAULT = False
MASK_AND_SCALE_FLAG_DEFAULT = False
TERMINAL_WIDTH_FRACTION = 0.9

TIMESTAMPS_FREQUENCY_DEFAULT = 'h'  # hours

LATITUDE_MINIMUM = -90
LATITUDE_MAXIMUM = 90  # in PVGIS : rowoffset
LONGITUDE_MINIMUM = -180
LONGITUDE_MAXIMUM = 180  # in PVGIS : coloffset
ELEVATION_MINIMUM = 0
ELEVATION_MAXIMUM = 8848
HORIZON_HEIGHT_UNIT = 'meters'  # Is it meters? ------------------------------
SOLAR_DECLINATION_MINIMUM = 0
SOLAR_DECLINATION_MAXIMUM = 90

SURFACE_TILT_MINIMUM = 0
SURFACE_TILT_MAXIMUM = 90
SURFACE_TILT_DEFAULT = 45  # degrees
OPTIMISE_SURFACE_TILT_FLAG_DEFAULT = False
OPTIMISE_SURFACE_GEOMETRY_FLAG_DEFAULT = False
SURFACE_ORIENTATION_MINIMUM = 0
SURFACE_ORIENTATION_MAXIMUM = 360
SURFACE_ORIENTATION_DEFAULT = 180  # Due south, counting from North

SOLAR_CONSTANT_MINIMUM = 1360
SOLAR_CONSTANT = 1360.8  # at mean Earth-Sun distance in W/m^2
SOLAR_CONSTANT_TOLERANCE = 0.5
SOLAR_CONSTANT_COLUMN_NAME = 'Solar constant'
AU = 1  # Earth-Sun distance in Astronomical Units
AU_UNIT = '㍳'
STEPHAN_BOLTZMANN_CONSTANT = 5.67e-8  # in W/m^2 K^4
EXTRATERRESTRIAL_IRRADIANCE_MIN = 1315  # 1315.2963089821737 for days_in_a_year = 365.25
EXTRATERRESTRIAL_IRRADIANCE_MAX = 1407  # 1406.3049813983132 for days_in_a_year = 365.25

RANDOM_DAY_FLAG_DEFAULT = False
RANDOM_DAY_SERIES_FLAG_DEFAULT = False
FRACTIONAL_YEAR_MINIMUM = 0
FRACTIONAL_YEAR_MAXIMUM = 2 * pi
DAY_OF_YEAR_COLUMN_NAME = "Day of year"
PERIGEE_OFFSET = 0.048869
PERIGEE_OFFSET_COLUMN_NAME = 'Perigee'
ECCENTRICITY_CORRECTION_FACTOR = 0.03344  # 0.01672
ECCENTRICITY_CORRECTION_FACTOR_COLUMN_NAME = 'Eccentricity'
DISTANCE_CORRECTION_COLUMN_NAME = "Distance correction"

TERM_N_IN_SHADE = 0.25227
TERM_N_COLUMN_NAME = 'term N'
KB_RATIO_COLUMN_NAME = 'Kb'

LINKE_TURBIDITY_MINIMUM = 0
LINKE_TURBIDITY_MAXIMUM = 8
LINKE_TURBIDITY_DEFAULT = 2  # to get going for now
LINKE_TURBIDITY_TIME_SERIES_DEFAULT = LINKE_TURBIDITY_DEFAULT  # to get going for now
LINKE_TURBIDITY_UNIT = UNITLESS
LINKE_TURBIDITY_COLUMN_NAME = 'Linke'
LINKE_TURBIDITY_ADJUSTED_COLUMN_NAME = 'Linke′'
OPTICAL_AIR_MASS_DEFAULT = 2
OPTICAL_AIR_MASS_TIME_SERIES_DEFAULT = OPTICAL_AIR_MASS_DEFAULT
OPTICAL_AIR_MASS_UNIT = UNITLESS
OPTICAL_AIR_MASS_COLUMN_NAME = 'Air mass'
RAYLEIGH_OPTICAL_THICKNESS_COLUMN_NAME = 'Rayleigh'
RAYLEIGH_OPTICAL_THICKNESS_UNIT = UNITLESS
ATMOSPHERIC_REFRACTION_FLAG_DEFAULT = True

REFRACTED_SOLAR_ZENITH_ANGLE_DEFAULT = 1.5853349194640094  # radians
REFRACTED_SOLAR_ALTITUDE_COLUMN_NAME = 'Refracted alt.'

MEAN_GROUND_ALBEDO_DEFAULT = 2
TIME_OFFSET_GLOBAL_DEFAULT = 0
HOUR_OFFSET_DEFAULT = 0

NO_SOLAR_INCIDENCE = 0  # Solar incidence when shadow is detected

TEMPERATURE_UNIT = '℃'
TEMPERATURE_DEFAULT = 14  # global average surface air temperature, Celsius degrees
TEMPERATURE_AT_STANDARD_TEST_CONDITIONS = 25 # Cell temperature under standard test conditions, Celsius degrees
TEMPERATURE_COLUMN_NAME = 'Temperature ℃ '#
TEMPERATURE_ADJUSTED_COLUMN_NAME = 'Temperature′ ℃'
TEMPERATURE_DEVIATION_COLUMN_NAME = 'Temperature ≏℃ '  # for the PV module's temperature model

WIND_SPEED_DEFAULT = 0
WIND_SPEED_UNIT = '㎧'#m/s
WIND_SPEED_COLUMN_NAME = 'Wind speed 🌬'
ALBEDO_DEFAULT = 0.2
ALBEDO_COLUMN_NAME = 'Albedo'

PHOTOVOLTAIC_MODULE_DEFAULT = 'cSi:Free standing'
SYSTEM_EFFICIENCY_DEFAULT = 0.86
EFFICIENCY_DEFAULT = 0.86
EFFICIENCY = 'Efficiency'
EFFICIENCY_COLUMN_NAME = 'Efficiency %'
EFFICIENCY_FACTOR = 'Factor'
EFFICIENCY_FACTOR_COLUMN_NAME = 'Factor %'
SPECTRAL_FACTOR_COLUMN_NAME = 'Spectral factor %'
LOSS_NAME = 'Loss'

LONGITUDE = 'Longitude'
LATITUDE = 'Latitude'
LONGITUDE_NAME = 'Longitude'
LATITUDE_NAME = 'Latitude'
TIME_ALGORITHM_NAME = 'Timing'
DECLINATION_NAME = 'Declination'
HOUR_ANGLE_NAME = 'Hour Angle'
POSITION_ALGORITHM_NAME = 'Positioning'
ZENITH_NAME = 'Zenith'
ALTITUDE_NAME = 'Altitude'
AZIMUTH_NAME = 'Azimuth'
SURFACE_TILT_NAME = 'Tilt'
SURFACE_ORIENTATION_NAME = 'Orientation'
INCIDENCE_NAME = 'Incidence'
SOLAR_TIME_NAME = 'Solar Time'

UNITS_NAME = 'Units'
UNITLESSS_NAME = UNITLESS

TITLE_KEY_NAME = 'Title'
LONGITUDE_COLUMN_NAME = LONGITUDE_NAME + ' ϑ'
LATITUDE_COLUMN_NAME = LATITUDE_NAME + ' ϕ'
TIME_ALGORITHM_COLUMN_NAME = TIME_ALGORITHM_NAME + ' ⏲'  # Algorithm
DECLINATION_COLUMN_NAME = DECLINATION_NAME + ' ∢'
HOUR_ANGLE_COLUMN_NAME = HOUR_ANGLE_NAME + ' 🕛' 
POSITION_ALGORITHM_COLUMN_NAME = POSITION_ALGORITHM_NAME + ' ⯐'  # Algorithm
ZENITH_COLUMN_NAME = ZENITH_NAME + ' ⦭' 
ALTITUDE_COLUMN_NAME = ALTITUDE_NAME + ' ⦩'
AZIMUTH_COLUMN_NAME = AZIMUTH_NAME + ' ⭮'  #' ⦬' 
AZIMUTH_DIFFERENCE_COLUMN_NAME = AZIMUTH_NAME + ' Δ⦬'
INCIDENCE_COLUMN_NAME = INCIDENCE_NAME + ' ⦡'
INCIDENCE_ALGORITHM_COLUMN_NAME = INCIDENCE_NAME + ' algorithm'
INCIDENCE_DEFINITION = INCIDENCE_NAME + ' definition'
SOLAR_TIME_COLUMN_NAME = '' + SOLAR_TIME_NAME
SURFACE_TILT_COLUMN_NAME = SURFACE_TILT_NAME + ' ∡' 
SURFACE_ORIENTATION_COLUMN_NAME = SURFACE_ORIENTATION_NAME + ' ↻' 
LOSS_COLUMN_NAME = '' + LOSS_NAME

UNITS_COLUMN_NAME = 'Units'
UNITLESSS_COLUMN_NAME = UNITLESS + ' Column'

NOT_AVAILABLE_COLUMN_NAME = 'NA'
NOT_AVAILABLE = 'NA'
OUT_OF_RANGE_INDICES_COLUMN_NAME = 'Out-of-range'

IRRADIANCE_UNITS = 'W/m²'
IRRADIANCE_COLUMN_NAME = 'Irradiance ⌇'
RELATIVE_IRRADIANCE_COLUMN_NAME = 'Irradiance ⌇%'
LOG_RELATIVE_IRRADIANCE_COLUMN_NAME = 'ln(Irradiance ⌇%)'
NEGATIVE_RELATIVE_IRRADIANCE_COLUMN_NAME = '% Irradiance < 0'

ALGORITHM_NAME = 'Algorithm'
ALGORITHM_COLUMN_NAME = ALGORITHM_NAME
POWER_ALGORITHM_COLUMN_NAME = ALGORITHM_NAME + ' ⌁' 
TEMPERATURE_ALGORITHM_COLUMN_NAME = ALGORITHM_NAME + ' 🌡' 

IRRADIANCE_SOURCE_COLUMN_NAME = 'Irradiance source'  # Model or external data ?
IRRADIANCE_ALGORITHM_HOFIERKA_2002 = 'Hofierka, 2002'

# acronyms in PVGIS' C source code commented
POWER_AT_STANDARD_TEST_CONDITIONS = 94.804  # P_STC
VOLTAGE_AT_STANDARD_TEST_CONDITIONS = 34.6  # V_STC
VOLTAGE_AT_STANDARD_TEST_CONDITIONS_COEFFICIENT_1 = 1.15  # C1
VOLTAGE_AT_STANDARD_TEST_CONDITIONS_COEFFICIENT_2 = -0.32  # C2
CURRENT_AT_STANDARD_TEST_CONDITIONS = 2.74  # I_STC
CURRENT_AT_STANDARD_TEST_CONDITIONS_TEMPERATURE_COEFFICIENT = 0.0033  # ALPHA_VM
VOLTAGE_AT_STANDARD_TEST_CONDITIONS_TEMPERATURE_COEFFICIENT = -0.159  # BETA_VM

RADIATION_CUTOFF_THRESHHOLD = 0
DIRECT_CURRENT = '⎓'
DIRECT_CURRENT_COLUMN_NAME = 'STC ⎓'
VOLTAGE_COLUMN_NAME = 'STC ⚡'
POWER_UNIT = '㎾'
ENERGY_UNIT = 'kWh'
PHOTOVOLTAIC_POWER = 'Power'
PHOTOVOLTAIC_POWER_COLUMN_NAME = PHOTOVOLTAIC_POWER + ' ⌁'
EFFECTIVE_DIRECT_IRRADIANCE_COLUMN_NAME = 'Direct ⭍'
EFFECTIVE_DIFFUSE_IRRADIANCE_COLUMN_NAME = 'Diffuse 🗤⭍'
EFFECTIVE_REFLECTED_IRRADIANCE_COLUMN_NAME = 'Reflected ☈⭍'#☇

GLOBAL_IRRADIANCE_NAME = 'Global'
GLOBAL_INCLINED_IRRADIANCE = GLOBAL_IRRADIANCE_NAME
GLOBAL_INCLINED_IRRADIANCE_COLUMN_NAME = GLOBAL_IRRADIANCE_NAME + ' ∡'#⍼
GLOBAL_HORIZONTAL_IRRADIANCE_COLUMN_NAME = GLOBAL_IRRADIANCE_NAME + ' ⭸'

DIRECT_INCLINED_IRRADIANCE_COLUMN_NAME = 'Direct ∡'
DIRECT_HORIZONTAL_IRRADIANCE_COLUMN_NAME = 'Direct ⭸' # ⤓
DIRECT_NORMAL_IRRADIANCE_COLUMN_NAME = 'Direct ⦜'

DIFFUSE_INCLINED_IRRADIANCE = 'Diffuse inclined'
DIFFUSE_HORIZONTAL_IRRADIANCE = 'Diffuse horizontal'
DIFFUSE_CLEAR_SKY_IRRADIANCE = 'Diffuse clear-sky'
DIFFUSE_INCLINED_IRRADIANCE_COLUMN_NAME = 'Diffuse ∡'#🗤⟀
DIFFUSE_INCLINED_IRRADIANCE_BEFORE_LOSS_COLUMN_NAME = 'Dffs ∡ no-loss'#🗤⟀
DIFFUSE_HORIZONTAL_IRRADIANCE_COLUMN_NAME = 'Diffuse ⭸'
DIFFUSE_CLEAR_SKY_IRRADIANCE_COLUMN_NAME = 'Diffuse ☀'

REFLECTED_INCLINED_IRRADIANCE = 'Reflected'#∡
REFLECTED_INCLINED_IRRADIANCE_COLUMN_NAME = 'Reflected ∡'#☇⭚∡'
REFLECTED_HORIZONTAL_IRRADIANCE_COLUMN_NAME = 'Reflected ⭸'#☇⭚⭛


VIEW_FRACTION = "View %fraction"
VIEW_FRACTION_COLUMN_NAME = "View %"

EXTRATERRESTRIAL_NORMAL_IRRADIANCE = 'Extra Normal'
EXTRATERRESTRIAL_HORIZONTAL_IRRADIANCE = 'Extra Horizontal'
EXTRATERRESTRIAL_NORMAL_IRRADIANCE_COLUMN_NAME = 'Extra ⦜'#⌇
EXTRATERRESTRIAL_HORIZONTAL_IRRADIANCE_COLUMN_NAME = 'Extra ⭸'#⌇

ABOVE_HORIZON_COLUMN_NAME = "Above horizon"
LOW_ANGLE_COLUMN_NAME = "Low angle"
BELOW_HORIZON_COLUMN_NAME = "Below horizon"
SHADE_COLUMN_NAME = 'Shade'
COMPLEMENTARY_INCIDENCE_ANGLE_DEFAULT = True

# from PVGIS

ANGULAR_LOSS_COEFFICIENT = 0.155
ANGULAR_LOSS_FACTOR_FLAG_DEFAULT = True
EARTHRADIUS = 6371000.  # Earth radius in meters
UNDEFINED = 0.
UNDEFINED_Z = -9999.  # Out of range value?

angular_loss_denominator = 0.155

SCALING_FACTOR = 150
inverse_scale_constant = 1 / SCALING_FACTOR

UNDEF = float('nan')
double_numpi = 2 * np.pi
half_numpi = 0.5 * np.pi

pi_half = pi / 2  # Half of π
pi2 = pi * 2  # 2π
deg2rad = pi / 180  # Conversion factor from degrees to radians
rad2deg = 180 / pi  # Conversion factor from radians to degrees

PERFORMANCE_RATIO = 0.68
FIRSTYEAR = 2007
LASTYEAR = 2014
DUST_TRANSMITTANCE = 1.00
TEMPERATURE_INTERVAL = 1
T_COEFF = 0.035
THRESHOLD = 0.0001
INVERTER_EFF = 0.97
HOUR_ANGLE = pi / 12.0
UNDEF = 0.0  # undefined value for terrain aspect
UNDEFZ = -9999.0  # undefined value for NULL
SKIP = "1"
BIG = 1e20
EPS = 1e-4
STEP = "0.5"
MAX_YEARS = 20
START_VOLTAGE = 14.5
# TILE_SIZE = 2.5
# FIRST_EAST_TILE = 73
DEFAULT_CONSUMPTION_FILE = "hourlyconsumption.txt"
DEFAULT_COEFFICIENTS_FILE = "csi.coeffs"
DEFAULT_POWER_MATRIX_FILE = "matrix_voltages.csv"
DEFAULT_CHARGE_MATRIX_FILE = "battery_voltage.csv"
RADIATION_CUTOFF = 30.0

daysInMonth = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
MAX_CURRENTS = 20
MAX_STATES = 20
chargeMatrix = [0.0] * (MAX_CURRENTS * MAX_STATES)

systemEfficiency_global = 1.0
