"""
This `paramaters.yaml` YAML file describes the definition of custom data classes
required by `pvgisprototype`'s application programming interface (API) and,
hence, subsequently by the command line interface (CLI) and the Web API
components.

The content is parsed and converted into a native Python dictionary at
installation time.  ::: FIXME -- ToDo ! :::

The definition of a custom data class includes type, initial values, units, and
a textual description. The content is organized in sections : 'Where?',
  'When?', 'Atmospheric properties', 'Earth orbit' and more.

Each custom data class is described by the following (nested) key-value pairs:

    - value       : 'type' of and 'initial' value
    - unit        : 'type' of and 'initial' value
    - symbol      : used to visually distinguish a parameter
    - description : textual description of the parameter supported by the class

See Also
--------
- Python's PyYAML library for YAML file parsing:
  https://pypi.org/project/PyYAML/

Examples
--------
- Longitude:
    value:
        type: Optional[float]
        initial:
    unit:
        type: Optional[str]
        initial:
    symbol: Λ
    description: "The angle between a point on the Earth's surface and the meridian plane,
                  ranging from 0° at the Prime Meridian to 180° east or west."
"""

# Where ?

Longitude:
  value:
    type: float
    initial:
  unit:
    type: str
    initial:
  symbol:
    type: str
    initial: Λ
  desription:
    type: str
    initial: "The angle between a point on the Earth's surface and the meridian plane,
    with its value ranging from 0° at the Prime Meridian in Greenwich, England, to 180°
    east or west."

Latitude:
  value:
    type: float
    initial: 
  unit:
    type: str
    initial:
  symbol:
    type: str
    initial: Φ
  desription:
    type: str
    initial: "The angle between a point on the Earth's surface and the equatorial plane.
    It indicates a location's distance north or south of the equator, ranging from 0°
    at the Equator to 90° North or South at the poles."

Elevation:
  value:
    type: float
    initial:
  unit:
    type: str
    initial: meters
  symbol:
    type: str
    initial: z
  desription:
    type: str
    initial: "The height of a geographic point above a fixed reference point, commonly the mean sea level."

# When?

# Atmospheric properties

AtmosphericRefraction:
  value:
    type: float
    initial:
  unit:
    type: str
    initial:

# Earth orbit

PerigeeOffset:
  value:
    type: float
    initial: 0.048869
  unit:
    type: str
    initial: radians

EccentricityCorrectionFactor:
  value:
    type: float
    initial: 0.03344
  unit:
    type: str
    initial: radians

# Solar time

EquationOfTime:
  value:
    type: Union[ndarray, float]
    initial:
  unit:
    type: str
    initial: minutes

SolarHourAngle:
  value:
    type: Union[ndarray, float]
    initial:
  unit:
    type: str
    initial:
  position_algorithm:
    type: str
    initial:
  timing_algorithm:
    type: str
    initial:
  min_degrees:
    type: float
    initial: -180
  max_degrees:
    type: float
    initial: 180

EventHourAngle:
  value:
    type: Union[ndarray, float]
    initial:
  unit:
    type: str
    initial:

HourAngleSunrise:
  value:
    type: float
    initial:
  unit:
    type: str
    initial:

# Solar position

FractionalYear:
  value:
    type: Union[ndarray, float]
    initial:
  unit:
    type: str
    initial:
  min_degrees:
    type: float
    initial: 0
  max_degrees:
    type: float
    initial: 360

SolarDeclination:
  value:
    type: Union[ndarray, float]
    initial:
  unit:
    type: str
    initial:
  position_algorithm:
    type: str
    initial:
  timing_algorithm:
    type: str
    initial:
  min_degrees:
    type: float
    initial: -23.44
  max_degrees:
    type: float
    initial: 23.44

SolarZenith:
  value:
    type: Union[ndarray, float]
    initial:
  unit:
    type: str
    initial:
  position_algorithm:
    type: str
    initial:
  timing_algorithm:
    type: str
    initial:
  min_degrees:
    type: float
    initial: 0
  max_degrees:
    type: float
    initial: 180.836518

RefractedSolarZenith:
  value:
    type: float
    initial: 1.5853349194640094
  unit:
    type: str
    initial: radians

SolarAltitude:
  value:
    type: Union[ndarray, float]
    initial:
  unit:
    type: str
    initial:
  position_algorithm:
    type: str
    initial:
  timing_algorithm:
    type: str
    initial:
  min_radians:
    type: float
    initial: -3.15
  max_radians:
    type: float
    initial: 3.15
  min_degrees:
    type: float
    initial: -90
  max_degrees:
    type: float
    initial: 90
    
RefractedSolarAltitude:
  value:
    type: Union[ndarray, float]
    initial:
  unit:
    type: str
    initial: radians

TemperatureSeries:
  value:
    type: Union[ndarray, float]
    initial:
  unit:
    type: str
    initial: Celsius

WindSpeedSeries:
  value:
    type: Union[ndarray, float]
    initial:
  unit:
    type: str
    initial: m/s

LinkeTurbidityFactor:
  value:
    type: Union[ndarray, float]
    initial:
  unit:
    type: str
    initial: unitless

OpticalAirMass:
  value:
    type: Union[ndarray, float]
    initial:
  unit:
    type: str
    initial: unitless

RayleighThickness:
  value:
    type: Union[ndarray, float]
    initial:
  unit:
    type: str
    initial: unitless

SolarAzimuth:
  value:
    type: Union[ndarray, float]
    initial:
  unit:
    type: str
    initial:
  position_algorithm:
    type: str
    initial:
  timing_algorithm:
    type: str
    initial:
  min_degrees:
    type: float
    initial: 0
  max_degrees:
    type: float
    initial: 360

CompassSolarAzimuth:
  value:
    type: float
    initial:
  unit:
    type: str
    initial:

SolarPosition:
  value:
    type: float
    initial:
  unit:
    type: str
    initial:

SolarIncidence:
  value:
    type: Union[ndarray, float]
    initial:
  unit:
    type: str
    initial:
  position_algorithm:
    type: str
    initial:
  timing_algorithm:
    type: str
    initial:

# How ?

RelativeLongitude:
  value:
    type: float
    initial:
  unit:
    type: str
    initial:

TimeOffset:
  value:
    type: Union[ndarray, float]
    initial:
  unit:
    type: str
    initial: minutes

HorizonHeight:
  value:
    type: float
    initial:
  unit:
    type: str
    initial:

# Surface

SurfaceTilt:
  value:
    type: float
    initial: 45
  unit:
    type: str
    initial: 'degrees'

SurfaceOrientation:
  value:
    type: float
    initial: 180.0
  unit:
    type: str
    initial: 'degrees'
